name: ld_learn
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localization: ^0.2.0
  jailbreak_root_detection: ^1.1.5
  local_auth: ^2.2.0
  internet_connection_checker_plus: ^2.5.1
  flutter_secure_storage: ^9.2.2
  get: ^4.6.6
  flutter_screenutil: ^5.9.3
  flutter_localizations:
    sdk: flutter
  http: ^1.2.2
  firebase_core: ^2.25.4
  firebase_messaging: ^14.7.15
  path: ^1.9.0
  sqflite_sqlcipher: ^3.1.0+1
  pointycastle: ^3.9.1
  protobuf: ^3.1.0
  fixnum: ^1.1.0
  # qr_code_scanner: ^1.0.1
  # qr_flutter: ^4.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0


flutter:
  uses-material-design: true
