// Històric del dispositius de l'usuari.
// createdAt: 24/09/10 dm. JIQ

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.32.0
// 	protoc        v4.25.1
// source: usrmod/usr_fcm_history.proto

package __

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Representació de l'històric de tokens Firebase.
type UsrFcmHistory struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	BaseEntity *BaseEntity `protobuf:"bytes,1,opt,name=base_entity,json=baseEntity,proto3" json:"base_entity,omitempty"`
	Token      string      `protobuf:"bytes,2,opt,name=token,proto3" json:"token,omitempty"`
	Device     *UsrDevice  `protobuf:"bytes,3,opt,name=device,proto3" json:"device,omitempty"`
	Since      *Timestamp  `protobuf:"bytes,4,opt,name=since,proto3,oneof" json:"since,omitempty"`
	LastOne    bool        `protobuf:"varint,5,opt,name=last_one,json=lastOne,proto3" json:"last_one,omitempty"`
}

func (x *UsrFcmHistory) Reset() {
	*x = UsrFcmHistory{}
	if protoimpl.UnsafeEnabled {
		mi := &file_usrmod_usr_fcm_history_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UsrFcmHistory) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UsrFcmHistory) ProtoMessage() {}

func (x *UsrFcmHistory) ProtoReflect() protoreflect.Message {
	mi := &file_usrmod_usr_fcm_history_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UsrFcmHistory.ProtoReflect.Descriptor instead.
func (*UsrFcmHistory) Descriptor() ([]byte, []int) {
	return file_usrmod_usr_fcm_history_proto_rawDescGZIP(), []int{0}
}

func (x *UsrFcmHistory) GetBaseEntity() *BaseEntity {
	if x != nil {
		return x.BaseEntity
	}
	return nil
}

func (x *UsrFcmHistory) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

func (x *UsrFcmHistory) GetDevice() *UsrDevice {
	if x != nil {
		return x.Device
	}
	return nil
}

func (x *UsrFcmHistory) GetSince() *Timestamp {
	if x != nil {
		return x.Since
	}
	return nil
}

func (x *UsrFcmHistory) GetLastOne() bool {
	if x != nil {
		return x.LastOne
	}
	return false
}

// Representació d'una llista de tokens d'un dispositiu.
type UsrFcmTokenaList struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Elms []*UsrFcmHistory `protobuf:"bytes,1,rep,name=elms,proto3" json:"elms,omitempty"`
}

func (x *UsrFcmTokenaList) Reset() {
	*x = UsrFcmTokenaList{}
	if protoimpl.UnsafeEnabled {
		mi := &file_usrmod_usr_fcm_history_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UsrFcmTokenaList) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UsrFcmTokenaList) ProtoMessage() {}

func (x *UsrFcmTokenaList) ProtoReflect() protoreflect.Message {
	mi := &file_usrmod_usr_fcm_history_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UsrFcmTokenaList.ProtoReflect.Descriptor instead.
func (*UsrFcmTokenaList) Descriptor() ([]byte, []int) {
	return file_usrmod_usr_fcm_history_proto_rawDescGZIP(), []int{1}
}

func (x *UsrFcmTokenaList) GetElms() []*UsrFcmHistory {
	if x != nil {
		return x.Elms
	}
	return nil
}

var File_usrmod_usr_fcm_history_proto protoreflect.FileDescriptor

var file_usrmod_usr_fcm_history_proto_rawDesc = []byte{
	0x0a, 0x1c, 0x75, 0x73, 0x72, 0x6d, 0x6f, 0x64, 0x2f, 0x75, 0x73, 0x72, 0x5f, 0x66, 0x63, 0x6d,
	0x5f, 0x68, 0x69, 0x73, 0x74, 0x6f, 0x72, 0x79, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x05,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x11, 0x62, 0x61, 0x73, 0x65, 0x5f, 0x65, 0x6e, 0x74, 0x69,
	0x74, 0x79, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x0f, 0x74, 0x69, 0x6d, 0x65, 0x73, 0x74,
	0x61, 0x6d, 0x70, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x17, 0x75, 0x73, 0x72, 0x6d, 0x6f,
	0x64, 0x2f, 0x75, 0x73, 0x72, 0x5f, 0x64, 0x65, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x22, 0xd5, 0x01, 0x0a, 0x0d, 0x55, 0x73, 0x72, 0x46, 0x63, 0x6d, 0x48, 0x69, 0x73,
	0x74, 0x6f, 0x72, 0x79, 0x12, 0x32, 0x0a, 0x0b, 0x62, 0x61, 0x73, 0x65, 0x5f, 0x65, 0x6e, 0x74,
	0x69, 0x74, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x11, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x2e, 0x42, 0x61, 0x73, 0x65, 0x45, 0x6e, 0x74, 0x69, 0x74, 0x79, 0x52, 0x0a, 0x62, 0x61,
	0x73, 0x65, 0x45, 0x6e, 0x74, 0x69, 0x74, 0x79, 0x12, 0x14, 0x0a, 0x05, 0x74, 0x6f, 0x6b, 0x65,
	0x6e, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x74, 0x6f, 0x6b, 0x65, 0x6e, 0x12, 0x28,
	0x0a, 0x06, 0x64, 0x65, 0x76, 0x69, 0x63, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x10,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x55, 0x73, 0x72, 0x44, 0x65, 0x76, 0x69, 0x63, 0x65,
	0x52, 0x06, 0x64, 0x65, 0x76, 0x69, 0x63, 0x65, 0x12, 0x2b, 0x0a, 0x05, 0x73, 0x69, 0x6e, 0x63,
	0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x10, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e,
	0x54, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x48, 0x00, 0x52, 0x05, 0x73, 0x69, 0x6e,
	0x63, 0x65, 0x88, 0x01, 0x01, 0x12, 0x19, 0x0a, 0x08, 0x6c, 0x61, 0x73, 0x74, 0x5f, 0x6f, 0x6e,
	0x65, 0x18, 0x05, 0x20, 0x01, 0x28, 0x08, 0x52, 0x07, 0x6c, 0x61, 0x73, 0x74, 0x4f, 0x6e, 0x65,
	0x42, 0x08, 0x0a, 0x06, 0x5f, 0x73, 0x69, 0x6e, 0x63, 0x65, 0x22, 0x3c, 0x0a, 0x10, 0x55, 0x73,
	0x72, 0x46, 0x63, 0x6d, 0x54, 0x6f, 0x6b, 0x65, 0x6e, 0x61, 0x4c, 0x69, 0x73, 0x74, 0x12, 0x28,
	0x0a, 0x04, 0x65, 0x6c, 0x6d, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x14, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x55, 0x73, 0x72, 0x46, 0x63, 0x6d, 0x48, 0x69, 0x73, 0x74, 0x6f,
	0x72, 0x79, 0x52, 0x04, 0x65, 0x6c, 0x6d, 0x73, 0x42, 0x04, 0x5a, 0x02, 0x2e, 0x2f, 0x62, 0x06,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_usrmod_usr_fcm_history_proto_rawDescOnce sync.Once
	file_usrmod_usr_fcm_history_proto_rawDescData = file_usrmod_usr_fcm_history_proto_rawDesc
)

func file_usrmod_usr_fcm_history_proto_rawDescGZIP() []byte {
	file_usrmod_usr_fcm_history_proto_rawDescOnce.Do(func() {
		file_usrmod_usr_fcm_history_proto_rawDescData = protoimpl.X.CompressGZIP(file_usrmod_usr_fcm_history_proto_rawDescData)
	})
	return file_usrmod_usr_fcm_history_proto_rawDescData
}

var file_usrmod_usr_fcm_history_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_usrmod_usr_fcm_history_proto_goTypes = []interface{}{
	(*UsrFcmHistory)(nil),    // 0: proto.UsrFcmHistory
	(*UsrFcmTokenaList)(nil), // 1: proto.UsrFcmTokenaList
	(*BaseEntity)(nil),       // 2: proto.BaseEntity
	(*UsrDevice)(nil),        // 3: proto.UsrDevice
	(*Timestamp)(nil),        // 4: proto.Timestamp
}
var file_usrmod_usr_fcm_history_proto_depIdxs = []int32{
	2, // 0: proto.UsrFcmHistory.base_entity:type_name -> proto.BaseEntity
	3, // 1: proto.UsrFcmHistory.device:type_name -> proto.UsrDevice
	4, // 2: proto.UsrFcmHistory.since:type_name -> proto.Timestamp
	0, // 3: proto.UsrFcmTokenaList.elms:type_name -> proto.UsrFcmHistory
	4, // [4:4] is the sub-list for method output_type
	4, // [4:4] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_usrmod_usr_fcm_history_proto_init() }
func file_usrmod_usr_fcm_history_proto_init() {
	if File_usrmod_usr_fcm_history_proto != nil {
		return
	}
	file_base_entity_proto_init()
	file_timestamp_proto_init()
	file_usrmod_usr_device_proto_init()
	if !protoimpl.UnsafeEnabled {
		file_usrmod_usr_fcm_history_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UsrFcmHistory); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_usrmod_usr_fcm_history_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UsrFcmTokenaList); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	file_usrmod_usr_fcm_history_proto_msgTypes[0].OneofWrappers = []interface{}{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_usrmod_usr_fcm_history_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_usrmod_usr_fcm_history_proto_goTypes,
		DependencyIndexes: file_usrmod_usr_fcm_history_proto_depIdxs,
		MessageInfos:      file_usrmod_usr_fcm_history_proto_msgTypes,
	}.Build()
	File_usrmod_usr_fcm_history_proto = out.File
	file_usrmod_usr_fcm_history_proto_rawDesc = nil
	file_usrmod_usr_fcm_history_proto_goTypes = nil
	file_usrmod_usr_fcm_history_proto_depIdxs = nil
}
