// Fitxer de definició proto per l'entitat EmoEmotion.
// createdAt: 24/09/23 dl. JIQ

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.34.2
// 	protoc        v5.28.2
// source: emomod/emo_entities.proto

package __

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Definició d'una emoció.
type EmoEmotion struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	BaseEntity *ModelEntity `protobuf:"bytes,1,opt,name=base_entity,json=baseEntity,proto3" json:"base_entity,omitempty"`
	NameKey    string       `protobuf:"bytes,2,opt,name=name_key,json=nameKey,proto3" json:"name_key,omitempty"`
	DescKey    *string      `protobuf:"bytes,3,opt,name=desc_key,json=descKey,proto3,oneof" json:"desc_key,omitempty"`
	Parent     *EmoEmotion  `protobuf:"bytes,4,opt,name=parent,proto3,oneof" json:"parent,omitempty"`
	Value      int32        `protobuf:"varint,5,opt,name=value,proto3" json:"value,omitempty"`
}

func (x *EmoEmotion) Reset() {
	*x = EmoEmotion{}
	if protoimpl.UnsafeEnabled {
		mi := &file_emomod_emo_entities_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *EmoEmotion) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EmoEmotion) ProtoMessage() {}

func (x *EmoEmotion) ProtoReflect() protoreflect.Message {
	mi := &file_emomod_emo_entities_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EmoEmotion.ProtoReflect.Descriptor instead.
func (*EmoEmotion) Descriptor() ([]byte, []int) {
	return file_emomod_emo_entities_proto_rawDescGZIP(), []int{0}
}

func (x *EmoEmotion) GetBaseEntity() *ModelEntity {
	if x != nil {
		return x.BaseEntity
	}
	return nil
}

func (x *EmoEmotion) GetNameKey() string {
	if x != nil {
		return x.NameKey
	}
	return ""
}

func (x *EmoEmotion) GetDescKey() string {
	if x != nil && x.DescKey != nil {
		return *x.DescKey
	}
	return ""
}

func (x *EmoEmotion) GetParent() *EmoEmotion {
	if x != nil {
		return x.Parent
	}
	return nil
}

func (x *EmoEmotion) GetValue() int32 {
	if x != nil {
		return x.Value
	}
	return 0
}

type EmoEmotions struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Error    *GbError      `protobuf:"bytes,1,opt,name=error,proto3,oneof" json:"error,omitempty"`
	Emotions []*EmoEmotion `protobuf:"bytes,2,rep,name=emotions,proto3" json:"emotions,omitempty"`
}

func (x *EmoEmotions) Reset() {
	*x = EmoEmotions{}
	if protoimpl.UnsafeEnabled {
		mi := &file_emomod_emo_entities_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *EmoEmotions) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EmoEmotions) ProtoMessage() {}

func (x *EmoEmotions) ProtoReflect() protoreflect.Message {
	mi := &file_emomod_emo_entities_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EmoEmotions.ProtoReflect.Descriptor instead.
func (*EmoEmotions) Descriptor() ([]byte, []int) {
	return file_emomod_emo_entities_proto_rawDescGZIP(), []int{1}
}

func (x *EmoEmotions) GetError() *GbError {
	if x != nil {
		return x.Error
	}
	return nil
}

func (x *EmoEmotions) GetEmotions() []*EmoEmotion {
	if x != nil {
		return x.Emotions
	}
	return nil
}

type EmoModuleLists struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Error    *GbError     `protobuf:"bytes,1,opt,name=error,proto3,oneof" json:"error,omitempty"`
	Moods    *EmoMoods    `protobuf:"bytes,2,opt,name=moods,proto3" json:"moods,omitempty"`
	Emotions *EmoEmotions `protobuf:"bytes,3,opt,name=emotions,proto3" json:"emotions,omitempty"`
}

func (x *EmoModuleLists) Reset() {
	*x = EmoModuleLists{}
	if protoimpl.UnsafeEnabled {
		mi := &file_emomod_emo_entities_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *EmoModuleLists) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EmoModuleLists) ProtoMessage() {}

func (x *EmoModuleLists) ProtoReflect() protoreflect.Message {
	mi := &file_emomod_emo_entities_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EmoModuleLists.ProtoReflect.Descriptor instead.
func (*EmoModuleLists) Descriptor() ([]byte, []int) {
	return file_emomod_emo_entities_proto_rawDescGZIP(), []int{2}
}

func (x *EmoModuleLists) GetError() *GbError {
	if x != nil {
		return x.Error
	}
	return nil
}

func (x *EmoModuleLists) GetMoods() *EmoMoods {
	if x != nil {
		return x.Moods
	}
	return nil
}

func (x *EmoModuleLists) GetEmotions() *EmoEmotions {
	if x != nil {
		return x.Emotions
	}
	return nil
}

// Definició d'un estat d'ànim.
type EmoMood struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	BaseEntity *ModelEntity `protobuf:"bytes,1,opt,name=base_entity,json=baseEntity,proto3" json:"base_entity,omitempty"`
	NameKey    string       `protobuf:"bytes,2,opt,name=name_key,json=nameKey,proto3" json:"name_key,omitempty"`
	DescKey    *string      `protobuf:"bytes,3,opt,name=desc_key,json=descKey,proto3,oneof" json:"desc_key,omitempty"`
	Value      int32        `protobuf:"varint,4,opt,name=value,proto3" json:"value,omitempty"`
}

func (x *EmoMood) Reset() {
	*x = EmoMood{}
	if protoimpl.UnsafeEnabled {
		mi := &file_emomod_emo_entities_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *EmoMood) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EmoMood) ProtoMessage() {}

func (x *EmoMood) ProtoReflect() protoreflect.Message {
	mi := &file_emomod_emo_entities_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EmoMood.ProtoReflect.Descriptor instead.
func (*EmoMood) Descriptor() ([]byte, []int) {
	return file_emomod_emo_entities_proto_rawDescGZIP(), []int{3}
}

func (x *EmoMood) GetBaseEntity() *ModelEntity {
	if x != nil {
		return x.BaseEntity
	}
	return nil
}

func (x *EmoMood) GetNameKey() string {
	if x != nil {
		return x.NameKey
	}
	return ""
}

func (x *EmoMood) GetDescKey() string {
	if x != nil && x.DescKey != nil {
		return *x.DescKey
	}
	return ""
}

func (x *EmoMood) GetValue() int32 {
	if x != nil {
		return x.Value
	}
	return 0
}

type EmoMoods struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Error *GbError   `protobuf:"bytes,1,opt,name=error,proto3,oneof" json:"error,omitempty"`
	Moods []*EmoMood `protobuf:"bytes,2,rep,name=moods,proto3" json:"moods,omitempty"`
}

func (x *EmoMoods) Reset() {
	*x = EmoMoods{}
	if protoimpl.UnsafeEnabled {
		mi := &file_emomod_emo_entities_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *EmoMoods) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EmoMoods) ProtoMessage() {}

func (x *EmoMoods) ProtoReflect() protoreflect.Message {
	mi := &file_emomod_emo_entities_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EmoMoods.ProtoReflect.Descriptor instead.
func (*EmoMoods) Descriptor() ([]byte, []int) {
	return file_emomod_emo_entities_proto_rawDescGZIP(), []int{4}
}

func (x *EmoMoods) GetError() *GbError {
	if x != nil {
		return x.Error
	}
	return nil
}

func (x *EmoMoods) GetMoods() []*EmoMood {
	if x != nil {
		return x.Moods
	}
	return nil
}

var File_emomod_emo_entities_proto protoreflect.FileDescriptor

var file_emomod_emo_entities_proto_rawDesc = []byte{
	0x0a, 0x19, 0x65, 0x6d, 0x6f, 0x6d, 0x6f, 0x64, 0x2f, 0x65, 0x6d, 0x6f, 0x5f, 0x65, 0x6e, 0x74,
	0x69, 0x74, 0x69, 0x65, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x05, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x1a, 0x10, 0x67, 0x62, 0x6c, 0x5f, 0x67, 0x6c, 0x6f, 0x62, 0x61, 0x6c, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x12, 0x6d, 0x6f, 0x64, 0x65, 0x6c, 0x5f, 0x65, 0x6e, 0x74, 0x69,
	0x74, 0x79, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0xda, 0x01, 0x0a, 0x0a, 0x45, 0x6d, 0x6f,
	0x45, 0x6d, 0x6f, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x33, 0x0a, 0x0b, 0x62, 0x61, 0x73, 0x65, 0x5f,
	0x65, 0x6e, 0x74, 0x69, 0x74, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x12, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x4d, 0x6f, 0x64, 0x65, 0x6c, 0x45, 0x6e, 0x74, 0x69, 0x74, 0x79,
	0x52, 0x0a, 0x62, 0x61, 0x73, 0x65, 0x45, 0x6e, 0x74, 0x69, 0x74, 0x79, 0x12, 0x19, 0x0a, 0x08,
	0x6e, 0x61, 0x6d, 0x65, 0x5f, 0x6b, 0x65, 0x79, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07,
	0x6e, 0x61, 0x6d, 0x65, 0x4b, 0x65, 0x79, 0x12, 0x1e, 0x0a, 0x08, 0x64, 0x65, 0x73, 0x63, 0x5f,
	0x6b, 0x65, 0x79, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x48, 0x00, 0x52, 0x07, 0x64, 0x65, 0x73,
	0x63, 0x4b, 0x65, 0x79, 0x88, 0x01, 0x01, 0x12, 0x2e, 0x0a, 0x06, 0x70, 0x61, 0x72, 0x65, 0x6e,
	0x74, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x11, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e,
	0x45, 0x6d, 0x6f, 0x45, 0x6d, 0x6f, 0x74, 0x69, 0x6f, 0x6e, 0x48, 0x01, 0x52, 0x06, 0x70, 0x61,
	0x72, 0x65, 0x6e, 0x74, 0x88, 0x01, 0x01, 0x12, 0x14, 0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65,
	0x18, 0x05, 0x20, 0x01, 0x28, 0x05, 0x52, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x42, 0x0b, 0x0a,
	0x09, 0x5f, 0x64, 0x65, 0x73, 0x63, 0x5f, 0x6b, 0x65, 0x79, 0x42, 0x09, 0x0a, 0x07, 0x5f, 0x70,
	0x61, 0x72, 0x65, 0x6e, 0x74, 0x22, 0x71, 0x0a, 0x0b, 0x45, 0x6d, 0x6f, 0x45, 0x6d, 0x6f, 0x74,
	0x69, 0x6f, 0x6e, 0x73, 0x12, 0x29, 0x0a, 0x05, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x0b, 0x32, 0x0e, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x47, 0x62, 0x45, 0x72,
	0x72, 0x6f, 0x72, 0x48, 0x00, 0x52, 0x05, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x88, 0x01, 0x01, 0x12,
	0x2d, 0x0a, 0x08, 0x65, 0x6d, 0x6f, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x18, 0x02, 0x20, 0x03, 0x28,
	0x0b, 0x32, 0x11, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x45, 0x6d, 0x6f, 0x45, 0x6d, 0x6f,
	0x74, 0x69, 0x6f, 0x6e, 0x52, 0x08, 0x65, 0x6d, 0x6f, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x42, 0x08,
	0x0a, 0x06, 0x5f, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x22, 0x9c, 0x01, 0x0a, 0x0e, 0x45, 0x6d, 0x6f,
	0x4d, 0x6f, 0x64, 0x75, 0x6c, 0x65, 0x4c, 0x69, 0x73, 0x74, 0x73, 0x12, 0x29, 0x0a, 0x05, 0x65,
	0x72, 0x72, 0x6f, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0e, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x2e, 0x47, 0x62, 0x45, 0x72, 0x72, 0x6f, 0x72, 0x48, 0x00, 0x52, 0x05, 0x65, 0x72,
	0x72, 0x6f, 0x72, 0x88, 0x01, 0x01, 0x12, 0x25, 0x0a, 0x05, 0x6d, 0x6f, 0x6f, 0x64, 0x73, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0f, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x45, 0x6d,
	0x6f, 0x4d, 0x6f, 0x6f, 0x64, 0x73, 0x52, 0x05, 0x6d, 0x6f, 0x6f, 0x64, 0x73, 0x12, 0x2e, 0x0a,
	0x08, 0x65, 0x6d, 0x6f, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32,
	0x12, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x45, 0x6d, 0x6f, 0x45, 0x6d, 0x6f, 0x74, 0x69,
	0x6f, 0x6e, 0x73, 0x52, 0x08, 0x65, 0x6d, 0x6f, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x42, 0x08, 0x0a,
	0x06, 0x5f, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x22, 0x9c, 0x01, 0x0a, 0x07, 0x45, 0x6d, 0x6f, 0x4d,
	0x6f, 0x6f, 0x64, 0x12, 0x33, 0x0a, 0x0b, 0x62, 0x61, 0x73, 0x65, 0x5f, 0x65, 0x6e, 0x74, 0x69,
	0x74, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x12, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x2e, 0x4d, 0x6f, 0x64, 0x65, 0x6c, 0x45, 0x6e, 0x74, 0x69, 0x74, 0x79, 0x52, 0x0a, 0x62, 0x61,
	0x73, 0x65, 0x45, 0x6e, 0x74, 0x69, 0x74, 0x79, 0x12, 0x19, 0x0a, 0x08, 0x6e, 0x61, 0x6d, 0x65,
	0x5f, 0x6b, 0x65, 0x79, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x6e, 0x61, 0x6d, 0x65,
	0x4b, 0x65, 0x79, 0x12, 0x1e, 0x0a, 0x08, 0x64, 0x65, 0x73, 0x63, 0x5f, 0x6b, 0x65, 0x79, 0x18,
	0x03, 0x20, 0x01, 0x28, 0x09, 0x48, 0x00, 0x52, 0x07, 0x64, 0x65, 0x73, 0x63, 0x4b, 0x65, 0x79,
	0x88, 0x01, 0x01, 0x12, 0x14, 0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x04, 0x20, 0x01,
	0x28, 0x05, 0x52, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x42, 0x0b, 0x0a, 0x09, 0x5f, 0x64, 0x65,
	0x73, 0x63, 0x5f, 0x6b, 0x65, 0x79, 0x22, 0x65, 0x0a, 0x08, 0x45, 0x6d, 0x6f, 0x4d, 0x6f, 0x6f,
	0x64, 0x73, 0x12, 0x29, 0x0a, 0x05, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x0b, 0x32, 0x0e, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x47, 0x62, 0x45, 0x72, 0x72, 0x6f,
	0x72, 0x48, 0x00, 0x52, 0x05, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x88, 0x01, 0x01, 0x12, 0x24, 0x0a,
	0x05, 0x6d, 0x6f, 0x6f, 0x64, 0x73, 0x18, 0x02, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x0e, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x45, 0x6d, 0x6f, 0x4d, 0x6f, 0x6f, 0x64, 0x52, 0x05, 0x6d, 0x6f,
	0x6f, 0x64, 0x73, 0x42, 0x08, 0x0a, 0x06, 0x5f, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x42, 0x04, 0x5a,
	0x02, 0x2e, 0x2f, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_emomod_emo_entities_proto_rawDescOnce sync.Once
	file_emomod_emo_entities_proto_rawDescData = file_emomod_emo_entities_proto_rawDesc
)

func file_emomod_emo_entities_proto_rawDescGZIP() []byte {
	file_emomod_emo_entities_proto_rawDescOnce.Do(func() {
		file_emomod_emo_entities_proto_rawDescData = protoimpl.X.CompressGZIP(file_emomod_emo_entities_proto_rawDescData)
	})
	return file_emomod_emo_entities_proto_rawDescData
}

var file_emomod_emo_entities_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_emomod_emo_entities_proto_goTypes = []any{
	(*EmoEmotion)(nil),     // 0: proto.EmoEmotion
	(*EmoEmotions)(nil),    // 1: proto.EmoEmotions
	(*EmoModuleLists)(nil), // 2: proto.EmoModuleLists
	(*EmoMood)(nil),        // 3: proto.EmoMood
	(*EmoMoods)(nil),       // 4: proto.EmoMoods
	(*ModelEntity)(nil),    // 5: proto.ModelEntity
	(*GbError)(nil),        // 6: proto.GbError
}
var file_emomod_emo_entities_proto_depIdxs = []int32{
	5,  // 0: proto.EmoEmotion.base_entity:type_name -> proto.ModelEntity
	0,  // 1: proto.EmoEmotion.parent:type_name -> proto.EmoEmotion
	6,  // 2: proto.EmoEmotions.error:type_name -> proto.GbError
	0,  // 3: proto.EmoEmotions.emotions:type_name -> proto.EmoEmotion
	6,  // 4: proto.EmoModuleLists.error:type_name -> proto.GbError
	4,  // 5: proto.EmoModuleLists.moods:type_name -> proto.EmoMoods
	1,  // 6: proto.EmoModuleLists.emotions:type_name -> proto.EmoEmotions
	5,  // 7: proto.EmoMood.base_entity:type_name -> proto.ModelEntity
	6,  // 8: proto.EmoMoods.error:type_name -> proto.GbError
	3,  // 9: proto.EmoMoods.moods:type_name -> proto.EmoMood
	10, // [10:10] is the sub-list for method output_type
	10, // [10:10] is the sub-list for method input_type
	10, // [10:10] is the sub-list for extension type_name
	10, // [10:10] is the sub-list for extension extendee
	0,  // [0:10] is the sub-list for field type_name
}

func init() { file_emomod_emo_entities_proto_init() }
func file_emomod_emo_entities_proto_init() {
	if File_emomod_emo_entities_proto != nil {
		return
	}
	file_gbl_global_proto_init()
	file_model_entity_proto_init()
	if !protoimpl.UnsafeEnabled {
		file_emomod_emo_entities_proto_msgTypes[0].Exporter = func(v any, i int) any {
			switch v := v.(*EmoEmotion); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_emomod_emo_entities_proto_msgTypes[1].Exporter = func(v any, i int) any {
			switch v := v.(*EmoEmotions); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_emomod_emo_entities_proto_msgTypes[2].Exporter = func(v any, i int) any {
			switch v := v.(*EmoModuleLists); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_emomod_emo_entities_proto_msgTypes[3].Exporter = func(v any, i int) any {
			switch v := v.(*EmoMood); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_emomod_emo_entities_proto_msgTypes[4].Exporter = func(v any, i int) any {
			switch v := v.(*EmoMoods); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	file_emomod_emo_entities_proto_msgTypes[0].OneofWrappers = []any{}
	file_emomod_emo_entities_proto_msgTypes[1].OneofWrappers = []any{}
	file_emomod_emo_entities_proto_msgTypes[2].OneofWrappers = []any{}
	file_emomod_emo_entities_proto_msgTypes[3].OneofWrappers = []any{}
	file_emomod_emo_entities_proto_msgTypes[4].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_emomod_emo_entities_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_emomod_emo_entities_proto_goTypes,
		DependencyIndexes: file_emomod_emo_entities_proto_depIdxs,
		MessageInfos:      file_emomod_emo_entities_proto_msgTypes,
	}.Build()
	File_emomod_emo_entities_proto = out.File
	file_emomod_emo_entities_proto_rawDesc = nil
	file_emomod_emo_entities_proto_goTypes = nil
	file_emomod_emo_entities_proto_depIdxs = nil
}
