-- Active: 1702757415250@@127.0.0.1@3306@sabina
CREATE DATABASE IF NOT EXISTS SABINA
CHARACTER SET utf8
COLLATE utf8_bin;

USE SABINA;

-- TAULA D'USUARIS
CREATE TABLE USERS (
    ID         INT AUTO_INCREMENT PRIMARY KEY,
    CREATED_AT DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    NAME       VARCHAR (100) NOT NULL,
    EMAIL      VARCHAR(100),
    PHONE      VARCHAR(50),
    USER_TYPE  INT NOT NULL,
    PERMISSIONS INT UNSIGNED NOT NULL DEFAULT 0 -- 32 flags de permissos.
);

CREATE INDEX USERS_NAME ON USERS(NAME);
CREATE INDEX USERS_EMAIL ON USERS(EMAIL);

-- TAULA DE DISPOSITIUS
CREATE TABLE DEVICES (
    ID         INT AUTO_INCREMENT PRIMARY KEY,
    CREATED_AT DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    USER_ID    INT NOT NULL REFERENCES USERS(ID),
    FCM_TOKEN  VARCHAR(255) NOT NULL,
    PHONE      VARCHAR(50)
);

CREATE INDEX DEVICES_TOKEN ON DEVICES(FCM_TOKEN);

-- TAULA D'HISTÒRIC DE TOKENS
CREATE TABLE TOKENS (
    ID          INT AUTO_INCREMENT PRIMARY KEY,
    CREATED_AT  DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    USER_ID     INT NOT NULL REFERENCES USERS(ID),
    FCM_TOKEN   VARCHAR(255) NOT NULL,
    STATE       CHAR(3) NOT NULL DEFAULT 'CAD',
    PREVIOUS_ID INT REFERENCES TOKENS(ID)
);

CREATE INDEX TOKENS_TOKEN ON TOKENS(FCM_TOKEN);

-- TAULA D'ADMINISTRADORS
CREATE TABLE ADMINS (
    ID          INT AUTO_INCREMENT PRIMARY KEY,
    CREATED_AT  DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    USER_ID     INT NOT NULL REFERENCES USERS(ID),
    ROOT        BOOL DEFAULT FALSE
    -- CAL ESTABLIR LA LLISTA DE PERMISOS DELS ADMINISTRADORS.
);

-- TAULA DE TERAPÈUTA
CREATE TABLE THERAPISTS (
    ID          INT AUTO_INCREMENT PRIMARY KEY,
    CREATED_AT  DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    USER_ID     INT NOT NULL REFERENCES USERS(ID)
);

-- TAULA DE PACIENTS
CREATE TABLE PATIENTS (
    ID          INT AUTO_INCREMENT PRIMARY KEY,
    CREATED_AT  DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    USER_ID     INT NOT NULL REFERENCES USERS(ID),
    MAIN_THR_ID INT NOT NULL REFERENCES THERAPISTS(ID),
    DERIVE_NOTF BOOLEAN NOT NULL DEFAULT FALSE
);

-- TAULA DE MALALTIES
CREATE TABLE DISEASES (
    ID          INT AUTO_INCREMENT PRIMARY KEY,
    CREATED_AT  DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CIE_10      VARCHAR(20) NOT NULL,
    TITLE       VARCHAR(400) NOT NULL
    -- SERIOUSNESS CHAR(2), -- 00. Lleu; 25. Moderat; 50. ... 75. Greu; 99. Profund
    -- DRUG_USE    CHAR(2)  -- 00. Nul; 25. Abstinència, 50. Lleu ; 75. Moderat; 99. Greu;
);

CREATE INDEX DISEASE_CIE_10 ON DISEASES(CIE_10);
CREATE INDEX DISEASE_TITLE ON DISEASES(TITLE);

-- TAULES DE CONVERSES
CREATE TABLE CHATS (
    ID           INT AUTO_INCREMENT PRIMARY KEY,
    CREATED_AT   DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CREATED_BY   INT NOT NULL REFERENCES USERS(ID),
    PATIENT_ID   INT REFERENCES PATIENTS(ID),
    FINISHED_AT  DATETIME
);

CREATE TABLE MESSAGES (
    ID           INT AUTO_INCREMENT PRIMARY KEY,
    CREATED_AT   DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CHAT_ID      INT NOT NULL REFERENCES CHATS(ID),
    INTERNAL     BOOLEAN NOT NULL DEFAULT TRUE,
    PATIENT_ID   INT REFERENCES PATIENTS(ID),
    THERAPIST_ID INT REFERENCES THERAPISTS(ID)
);

CREATE TABLE CHAT_MEMBERS (
    ID           INT AUTO_INCREMENT PRIMARY KEY,
    CREATED_AT   DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CHAT_ID      INT NOT NULL REFERENCES CHATS(ID),
    THERAPIST_ID INT NOT NULL REFERENCES THERAPISTS(ID)
);

-- TAULA DE DIAGNÒSTICS
CREATE TABLE DIAGNOSIS (
    ID           INT AUTO_INCREMENT PRIMARY KEY,
    CREATED_AT   DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    DISEASE_ID   INT NOT NULL REFERENCES DISEASES(ID),
    THERAPIST_ID INT NOT NULL REFERENCES THERAPISTS(ID),
    PATIENT_ID   INT NOT NULL REFERENCES PATIENTS(ID)
);

-- TAULA DE NOTES
CREATE TABLE NOTES (
    ID           INT AUTO_INCREMENT PRIMARY KEY,
    CREATED_AT   DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    THERAPIST_ID INT NOT NULL REFERENCES THERAPISTS(ID),
    DIAGNOSIS_ID INT REFERENCES DIAGNOSIS(ID),
    CHAT_ID      INT REFERENCES CHATS(ID),
    NOTE         VARCHAR(255) NOT NULL,
    PRIORITY     INT NOT NULL, -- 0. Crítica, ... 10. No tant important.
    PINNED       BOOLEAN NOT NULL DEFAULT FALSE
);
