DROP DATABASE IF EXISTS SABINA;
CREATE OR REPLACE DATABASE SABINA 
    CHARACTER set utf8mb4 collate utf8mb4_bin;
USE SABINA;

SET @loc_esid = "es";
SET @loc_caid = "ca";
SET @loc_enid = "en";
SET @loc_frid = "fr";
SET @loc_ptid = "pt";
SET @txt_esid = "es";
SET @txt_caid = "ca";
SET @txt_enid = "en";
SET @txt_frid = "fr";
SET @txt_ptid = "pt";

CREATE TABLE USER (
    ID         INT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
    CREATED_BY INT UNSIGNED NOT NULL REFERENCES USER(ID),
    CREATED_AT DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    UPDATED_BY INT UNSIGNED REFERENCES USER(ID),
    UPDATED_AT DATETIME,

    USER_TYPE     INT UNSIGNED NOT NULL,
    USER_STATE    INT UNSIGNED NOT NULL,
    PERMISSIONS   INT UNSIGNED NOT NULL DEFAULT 0,
    ALIAS         VARCHAR(100) NOT NULL,
    CERTIFICATE   BLOB,
    BIRTH_DATE    DATE,
    FIRST_KEY     INT,
    FIRST_CONN_AT DATETIME,
    LOCALE_CODE   VARCHAR(2) NOT NULL DEFAULT @loc_esid,
    THERAPIST_ID  INT UNSIGNED REFERENCES USER(ID),

    INDEX (CREATED_BY)
) ENGINE = InnoDB;

CREATE TABLE DEVICE (
    ID         INT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
    CREATED_BY INT UNSIGNED NOT NULL REFERENCES USER(ID),
    CREATED_AT DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    UPDATED_BY INT UNSIGNED REFERENCES USER(ID),
    UPDATED_AT DATETIME,

    DEVICE_TYPE  INT UNSIGNED NOT NULL,
    DEVICE_STATE INT UNSIGNED NOT NULL,
    FCM_TOKEN    VARCHAR(2048),
    OWNER_ID     INT UNSIGNED NOT NULL REFERENCES USER(ID)
) ENGINE = InnoDB;

ALTER TABLE USER
ADD COLUMN DEVICE_ID INT UNSIGNED REFERENCES DEVICE(ID);

CREATE TABLE FCM_HISTORY (
    ID         INT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
    CREATED_BY INT UNSIGNED NOT NULL REFERENCES USER(ID),
    CREATED_AT DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    UPDATED_BY INT UNSIGNED REFERENCES USER(ID),
    UPDATED_AT DATETIME,

    FCM_TOKEN  VARCHAR(2048) NOT NULL,
    DEVICE_ID  INT UNSIGNED NOT NULL REFERENCES DEVICE(ID),
    SINCE      DATETIME,
    LAST_ONE   BOOLEAN NOT NULL DEFAULT FALSE
) ENGINE = InnoDB;

CREATE TABLE TRANSLATION (
    ID INT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,

    TEXT_KEY    VARCHAR(100) NOT NULL,
    LOCALE_CODE VARCHAR(2) NOT NULL,
    LITERAL     VARCHAR(5000) NOT NULL,
    ITERATION   INT NOT NULL DEFAULT 0,
    
    UNIQUE(TEXT_KEY, LOCALE_CODE),
    FULLTEXT (LITERAL)
) ENGINE = InnoDB;

CREATE TABLE LIST_CATEGORY (
    ID         INT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
    CREATED_BY INT UNSIGNED NOT NULL REFERENCES USER(ID),
    CREATED_AT DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    UPDATED_BY INT UNSIGNED REFERENCES USER(ID),
    UPDATED_AT DATETIME,

    NAME_KEY  VARCHAR(100) NOT NULL,
    DESC_KEY  VARCHAR(100),
    PARENT_ID INT UNSIGNED REFERENCES LIST_CATEGORY(ID),

    INDEX(PARENT_ID)
) ENGINE = InnoDB;

CREATE TABLE OPTION_LIST (
    ID         INT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
    CREATED_BY INT UNSIGNED NOT NULL REFERENCES USER(ID),
    CREATED_AT DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    UPDATED_BY INT UNSIGNED REFERENCES USER(ID),
    UPDATED_AT DATETIME,

    NAME_KEY         VARCHAR(100) NOT NULL,
    DESC_KEY         VARCHAR(100) NOT NULL,
    LIST_CATEGORY_ID INT UNSIGNED NOT NULL REFERENCES LIST_CATEGORY(ID),
    IS_ALPHA         BOOLEAN NOT NULL DEFAULT FALSE
) ENGINE = InnoDB;

CREATE TABLE OPTION_ENTRY (
    ID         INT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
    CREATED_BY INT UNSIGNED NOT NULL REFERENCES USER(ID),
    CREATED_AT DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    UPDATED_BY INT UNSIGNED REFERENCES USER(ID),
    UPDATED_AT DATETIME,

    LIST_ID    INT UNSIGNED NOT NULL REFERENCES OPTION_LIST(ID),
    IDX        INT UNSIGNED NOT NULL,
    OPTION_KEY VARCHAR(100) NOT NULL,
    DESC_KEY   VARCHAR(100),
    IS_ALPHA   BOOLEAN NOT NULL DEFAULT FALSE
) ENGINE = InnoDB;

CREATE TABLE DSM_V (
    ID INT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,

    DNAME  VARCHAR(400) NOT NULL,
    CIE_10 VARCHAR(20) NOT NULL,

    FULLTEXT (DNAME),
    FULLTEXT (CIE_10)
) ENGINE = InnoDB;

CREATE TABLE DISEASE (
    ID         INT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
    CREATED_BY INT UNSIGNED NOT NULL REFERENCES USER(ID),
    CREATED_AT DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    UPDATED_BY INT UNSIGNED REFERENCES USER(ID),
    UPDATED_AT DATETIME,

    NAME_KEY  VARCHAR(100) NOT NULL,
    DESC_KEY  VARCHAR(100),
    DSM_V     INT UNSIGNED NOT NULL REFERENCES DSM_V(ID),
    THERAPIST INT UNSIGNED NOT NULL REFERENCES USER(ID),

    INDEX (DSM_V)
) ENGINE = InnoDB;

CREATE TABLE PHASE (
    ID         INT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
    CREATED_BY INT UNSIGNED NOT NULL REFERENCES USER(ID),
    CREATED_AT DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    UPDATED_BY INT UNSIGNED REFERENCES USER(ID),
    UPDATED_AT DATETIME,

    IDX        INT UNSIGNED NOT NULL,
    NAME_KEY   VARCHAR(100) NOT NULL,
    DESC_KEY   VARCHAR(100),
    DISEASE_ID INT UNSIGNED NOT NULL REFERENCES DISEASE(ID),

    INDEX (DISEASE_ID, IDX)
) ENGINE = InnoDB;

CREATE TABLE GOAL (
    ID         INT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
    CREATED_BY INT UNSIGNED NOT NULL REFERENCES USER(ID),
    CREATED_AT DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    UPDATED_BY INT UNSIGNED REFERENCES USER(ID),
    UPDATED_AT DATETIME,

    IDX      INT UNSIGNED NOT NULL,
    NAME_KEY VARCHAR(100) NOT NULL,
    DESC_KEY VARCHAR(100),
    PHASE_ID INT UNSIGNED NOT NULL REFERENCES PHASE(ID),

    INDEX (PHASE_ID, IDX)
) ENGINE = InnoDB;

CREATE TABLE RESOURCE (
    ID         INT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
    CREATED_BY INT UNSIGNED NOT NULL REFERENCES USER(ID),
    CREATED_AT DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    UPDATED_BY INT UNSIGNED REFERENCES USER(ID),
    UPDATED_AT DATETIME,

    NAME_KEY      VARCHAR(100) NOT NULL,
    DESC_KEY      VARCHAR(100),
    VERSION       INT UNSIGNED NOT NULL,
    ROOT_ID       INT UNSIGNED REFERENCES RESOURCE(ID),
    LOCALE_CODE   VARCHAR(2) NOT NULL,
    RESOURCE_TYPE INT UNSIGNED NOT NULL,
    INLINE_TEXT   VARCHAR(10000),
    LINK          VARCHAR(4096)
) ENGINE = InnoDB;

CREATE TABLE PHASE_RESOURCE (
    ID         INT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
    CREATED_BY INT UNSIGNED NOT NULL REFERENCES USER(ID),
    CREATED_AT DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    UPDATED_BY INT UNSIGNED REFERENCES USER(ID),
    UPDATED_AT DATETIME,

    DISEASE_ID  INT UNSIGNED NOT NULL REFERENCES DISEASE(ID),
    PHASE_ID    INT UNSIGNED REFERENCES PHASE(ID),
    RESOURCE_ID INT UNSIGNED NOT NULL REFERENCES RESOURCE(ID)
) ENGINE = InnoDB;

CREATE TABLE TRACKING (
    ID         INT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
    CREATED_BY INT UNSIGNED NOT NULL REFERENCES USER(ID),
    CREATED_AT DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    UPDATED_BY INT UNSIGNED REFERENCES USER(ID),
    UPDATED_AT DATETIME,

    NAME_KEY     VARCHAR(100) NOT NULL,
    DESC_KEY     VARCHAR(100),
    VERSION      INT UNSIGNED NOT NULL,
    THERAPIST_ID INT UNSIGNED NOT NULL REFERENCES USER(ID),
    ROOT_ID      INT UNSIGNED REFERENCES TRACKING(ID)
) ENGINE = InnoDB;

CREATE TABLE PHASE_TRACKING (
    ID         INT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
    CREATED_BY INT UNSIGNED NOT NULL REFERENCES USER(ID),
    CREATED_AT DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    UPDATED_BY INT UNSIGNED REFERENCES USER(ID),
    UPDATED_AT DATETIME,

    DISEASE_ID  INT UNSIGNED NOT NULL REFERENCES DISEASE(ID),
    PHASE_ID    INT UNSIGNED REFERENCES PHASE(ID),
    TRACKING_ID INT UNSIGNED NOT NULL REFERENCES TRACKING(ID)
) ENGINE = InnoDB;

CREATE TABLE TRACKING_COLUMN (
    ID         INT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
    CREATED_BY INT UNSIGNED NOT NULL REFERENCES USER(ID),
    CREATED_AT DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    UPDATED_BY INT UNSIGNED REFERENCES USER(ID),
    UPDATED_AT DATETIME,

    TRACKING_ID INT UNSIGNED NOT NULL REFERENCES TRACKING(ID),
    LIST_ID     INT UNSIGNED REFERENCES OPTION_LIST(ID),
    TITLE       VARCHAR(100) NOT NULL,
    COLUMN_TYPE INT UNSIGNED NOT NULL,
    MANDATORY   BOOLEAN NOT NULL DEFAULT TRUE,
    CUSTOMIZED  BOOLEAN NOT NULL DEFAULT FALSE
) ENGINE = InnoDB;

CREATE TABLE TEST_CATEGORY (
    ID         INT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
    CREATED_BY INT UNSIGNED NOT NULL REFERENCES USER(ID),
    CREATED_AT DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    UPDATED_BY INT UNSIGNED REFERENCES USER(ID),
    UPDATED_AT DATETIME,

    TITLE_KEY VARCHAR(100) NOT NULL,
    DESC_KEY  VARCHAR(100),
    PARENT_ID INT UNSIGNED REFERENCES TEST_CATEGORY(ID)
) ENGINE = InnoDB;

CREATE TABLE TEST (
    ID         INT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
    CREATED_BY INT UNSIGNED NOT NULL REFERENCES USER(ID),
    CREATED_AT DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    UPDATED_BY INT UNSIGNED REFERENCES USER(ID),
    UPDATED_AT DATETIME,

    CATEGORY_ID  INT UNSIGNED NOT NULL REFERENCES TEST_CATEGORY(ID),
    NAME_KEY     VARCHAR(100) NOT NULL,
    DESC_KEY     VARCHAR(100),
    INSTRS_KEY   VARCHAR(100),
    VERSION      INT UNSIGNED NOT NULL,
    ROOT_ID      INT UNSIGNED REFERENCES TEST(ID),
    THERAPIST_ID INT UNSIGNED NOT NULL REFERENCES USER(ID)
) ENGINE InnoDB;

CREATE TABLE QUESTION (
    ID         INT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
    CREATED_BY INT UNSIGNED NOT NULL REFERENCES USER(ID),
    CREATED_AT DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    UPDATED_BY INT UNSIGNED REFERENCES USER(ID),
    UPDATED_AT DATETIME,

    TEST_ID       INT UNSIGNED NOT NULL REFERENCES TEST(ID),
    QUESTION_TYPE INT UNSIGNED NOT NULL,
    BLOCK_ID      INT UNSIGNED REFERENCES QUESTION(ID),
    QUESTION_KEY  VARCHAR(100) NOT NULL,
    HELP_KEY      VARCHAR(100),
    MANDATORY     BOOLEAN NOT NULL DEFAULT TRUE,
    CUSTOMIZED    BOOLEAN NOT NULL DEFAULT FALSE
) ENGINE = InnoDB;

CREATE TABLE MOOD (
    ID         INT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
    CREATED_BY INT UNSIGNED NOT NULL REFERENCES USER(ID),
    CREATED_AT DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    UPDATED_BY INT UNSIGNED REFERENCES USER(ID),
    UPDATED_AT DATETIME,

    NAME_KEY VARCHAR(100) NOT NULL,
    DESC_KEY VARCHAR(100),
    VALUE    INT UNSIGNED NOT NULL DEFAULT 0
) ENGINE = InnoDB;

CREATE TABLE EMOTION (
    ID         INT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
    CREATED_BY INT UNSIGNED NOT NULL REFERENCES USER(ID),
    CREATED_AT DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    UPDATED_BY INT UNSIGNED REFERENCES USER(ID),
    UPDATED_AT DATETIME,

    NAME_KEY  VARCHAR(100) NOT NULL,
    DESC_KEY  VARCHAR(100),
    PARENT_ID INT UNSIGNED REFERENCES EMOTION(ID),
    VALUE     INT UNSIGNED NOT NULL
) ENGINE = InnoDB;

CREATE TABLE VISIT (
    ID         INT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
    CREATED_BY INT UNSIGNED NOT NULL REFERENCES USER(ID),
    CREATED_AT DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    UPDATED_BY INT UNSIGNED REFERENCES USER(ID),
    UPDATED_AT DATETIME,

    THERAPIST_ID INT UNSIGNED NOT NULL REFERENCES USER(ID),
    PATIENT_ID   INT UNSIGNED NOT NULL REFERENCES USER(ID),
    IS_FIRST     BOOLEAN NOT NULL DEFAULT FALSE,
    DATE_TIME    DATETIME NOT NULL,
    VISIT_TYPE   INT UNSIGNED NOT NULL,
    VISIT_STATE  INT UNSIGNED NOT NULL
) ENGINE = InnoDB;

CREATE TABLE DIAGNOSIS (
    ID         INT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
    CREATED_BY INT UNSIGNED NOT NULL REFERENCES USER(ID),
    CREATED_AT DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    UPDATED_BY INT UNSIGNED REFERENCES USER(ID),
    UPDATED_AT DATETIME,

    DISEASE_ID         INT UNSIGNED NOT NULL REFERENCES DISEASE(ID),
    THERAPIST_ID       INT UNSIGNED NOT NULL REFERENCES USER(ID),
    PATIENT_ID         INT UNSIGNED NOT NULL REFERENCES USER(ID),
    CURRENT_PHASE_ID   INT UNSIGNED NOT NULL REFERENCES DIAGNOSIS_PHASE(ID),
    DIAGNOSIS_STATE    INT UNSIGNED NOT NULL,
    ANNOTATIONS        VARCHAR(2048)
) ENGINE = InnoDB;

CREATE TABLE DIAGNOSIS_PHASE (
    ID         INT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
    CREATED_BY INT UNSIGNED NOT NULL REFERENCES USER(ID),
    CREATED_AT DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    UPDATED_BY INT UNSIGNED REFERENCES USER(ID),
    UPDATED_AT DATETIME,

    DIAGNOSIS_ID INT UNSIGNED NOT NULL REFERENCES DIAGNOSIS(ID),
    DISEASE_PHASE_ID INT UNSIGNED NOT NULL REFERENCES PHASE(ID),
    VISIT_ID     INT UNSIGNED NOT NULL REFERENCES VISIT(ID),
    PHASE_STATE  INT UNSIGNED NOT NULL,
    RELAPSE_ID   INT UNSIGNED REFERENCES DIAGNOSIS_PHASE(ID),
    ANNOTATIONS  VARCHAR(2048)
) ENGINE = InnoDB;

CREATE TABLE ACHIEVEMENT (
    ID         INT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
    CREATED_BY INT UNSIGNED NOT NULL REFERENCES USER(ID),
    CREATED_AT DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    UPDATED_BY INT UNSIGNED REFERENCES USER(ID),
    UPDATED_AT DATETIME,

    GOAL_ID     INT UNSIGNED NOT NULL REFERENCES GOAL(ID),
    DIAGNOSIS_PHASE_ID INT UNSIGNED NOT NULL REFERENCES DIAGNOSIS_PHASE(ID),
    ACV_STATE   INT UNSIGNED NOT NULL,
    RELAPSE_ID  INT UNSIGNED REFERENCES ACHIEVEMENT(ID),
    ANNOTATIONS VARCHAR(2048)
) ENGINE = InnoDB;

CREATE TABLE MATERIAL (
    ID         INT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
    CREATED_BY INT UNSIGNED NOT NULL REFERENCES USER(ID),
    CREATED_AT DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    UPDATED_BY INT UNSIGNED REFERENCES USER(ID),
    UPDATED_AT DATETIME,

    NAME_KEY      VARCHAR(100) NOT NULL,
    DESC_KEY      VARCHAR(100),
    PATIENT_ID    INT UNSIGNED NOT NULL REFERENCES USER(ID),
    RESOURCE_ID   INT UNSIGNED NOT NULL REFERENCES RESOURCE(ID),
    MATERIAL_TYPE INT UNSIGNED NOT NULL,
    PLAIN_KEY     VARCHAR(100),
    LINK          VARCHAR(4096)
) ENGINE = InnoDB;

CREATE TABLE PHASE_MATERIAL (
    ID         INT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
    CREATED_BY INT UNSIGNED NOT NULL REFERENCES USER(ID),
    CREATED_AT DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    UPDATED_BY INT UNSIGNED REFERENCES USER(ID),
    UPDATED_AT DATETIME,

    PATIENT_ID  INT UNSIGNED NOT NULL REFERENCES USER(ID),
    PHASE_RESOURCE_ID INT UNSIGNED NOT NULL REFERENCES PHASE_RESOURCE(ID)
) ENGINE InnoDB;

CREATE TABLE REGISTER (
    ID INT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
    CREATED_BY INT UNSIGNED NOT NULL REFERENCES USER(ID),
    CREATED_AT DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    UPDATED_BY INT UNSIGNED REFERENCES USER(ID),
    UPDATED_AT DATETIME,
    
    TRACKING_ID    INT UNSIGNED NOT NULL REFERENCES TRACKING(ID),
    PATIENT_ID     INT UNSIGNED NOT NULL REFERENCES USER(ID),
    FIRST_DATETIME DATETIME,
    LAST_DATETIME  DATETIME,
    REGISTER_STATE INT UNSIGNED NOT NULL
) ENGINE = InnoDB;

CREATE TABLE REGISTER_COLUMN (
    ID         INT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
    CREATED_BY INT UNSIGNED NOT NULL REFERENCES USER(ID),
    CREATED_AT DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    UPDATED_BY INT UNSIGNED REFERENCES USER(ID),
    UPDATED_AT DATETIME,

    REGISTER_ID  INT UNSIGNED NOT NULL REFERENCES REGISTER(ID),
    TRACK_COL_ID INT UNSIGNED NOT NULL REFERENCES TRACKING_COLUMN(ID),
    OPTION_ID    INT UNSIGNED REFERENCES OPTION_LIST(ID),
    EMOTION_ID   INT UNSIGNED REFERENCES EMOTION(ID),
    MOOD_ID      INT UNSIGNED REFERENCES MOOD(ID),
    VALUE        VARCHAR(4096)
) ENGINE = InnoDB;

CREATE TABLE PATIENT_TEST (
    ID         INT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
    CREATED_BY INT UNSIGNED NOT NULL REFERENCES USER(ID),
    CREATED_AT DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    UPDATED_BY INT UNSIGNED REFERENCES USER(ID),
    UPDATED_AT DATETIME,

    THERAPIST_ID INT UNSIGNED NOT NULL REFERENCES USER(ID),
    PATIENT_ID   INT UNSIGNED NOT NULL REFERENCES USER(ID),
    ASSIGNED_AT  DATETIME,
    COMPLETED_AT DATETIME,
    EVALUATED_BY INT UNSIGNED REFERENCES USER(ID),
    EVALUATED_AT DATETIME,
    EVALUATION   VARCHAR(4096)
) ENGINE = InnoDB;

CREATE TABLE ANSWER (
    ID         INT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
    CREATED_BY INT UNSIGNED NOT NULL REFERENCES USER(ID),
    CREATED_AT DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    UPDATED_BY INT UNSIGNED REFERENCES USER(ID),
    UPDATED_AT DATETIME,

    TEST_ID      INT UNSIGNED NOT NULL REFERENCES PATIENT_TEST(ID),
    QUESTION_ID  INT UNSIGNED NOT NULL REFERENCES QUESTION(ID),
    ANSWER       VARCHAR(2048),
    LIST_ID      INT UNSIGNED REFERENCES OPTION_LIST(ID),
    EMOTION_ID   INT UNSIGNED REFERENCES EMOTION(ID),
    MOOD_ID      INT UNSIGNED REFERENCES MOOD(ID),
    COMPLETED_AT DATETIME,
    EVALUATED_BY INT UNSIGNED REFERENCES USER(ID),
    EVALUATED_AT DATETIME,
    EVALUATION   VARCHAR(4096)
) ENGINE = InnoDB;

CREATE TABLE TASK (
    ID         INT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
    CREATED_BY INT UNSIGNED NOT NULL REFERENCES USER(ID),
    CREATED_AT DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    UPDATED_BY INT UNSIGNED REFERENCES USER(ID),
    UPDATED_AT DATETIME,

    THERAPIST_ID INT UNSIGNED NOT NULL REFERENCES USER(ID),
    PATIENT_ID   INT UNSIGNED NOT NULL REFERENCES USER(ID),
    TASK_TYPE    INT UNSIGNED NOT NULL,
    TASK_STATE   INT UNSIGNED NOT NULL,
    DESC_KEY     VARCHAR(2048) NOT NULL,
    TEST_ID      INT UNSIGNED REFERENCES PATIENT_TEST(ID),
    REGISTER_ID  INT UNSIGNED REFERENCES REGISTER(ID),
    RESOURCE_ID  INT UNSIGNED REFERENCES RESOURCE(ID),
    START_DATE   DATETIME,
    END_DATE     DATETIME
) ENGINE = InnoDB;

CREATE TABLE NOTIFICATION (
    ID         INT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
    CREATED_BY INT UNSIGNED NOT NULL REFERENCES USER(ID),
    CREATED_AT DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    UPDATED_BY INT UNSIGNED REFERENCES USER(ID),
    UPDATED_AT DATETIME,

    USER_ID      INT UNSIGNED NOT NULL REFERENCES USER(ID),
    NOTIFICATION VARCHAR(1024) NOT NULL,
    NTF_TYPE     INT UNSIGNED NOT NULL,
    NTF_STATE    INT UNSIGNED NOT NULL,
    TEST_ID      INT UNSIGNED REFERENCES PATIENT_TEST(ID),
    REGISTER_ID  INT UNSIGNED REFERENCES REGISTER(ID),
    RESOURCE_ID  INT UNSIGNED REFERENCES RESOURCE(ID)
) ENGINE = InnoDB;

INSERT INTO USER (
        USER_TYPE,
        USER_STATE,
        PERMISSIONS,
        ALIAS,
        CERTIFICATE,
        FIRST_KEY,
        FIRST_CONN_AT,
        LOCALE_CODE,
        CREATED_BY,
        CREATED_AT
    )
VALUES (
        1,
        1,
        4294967295,
        "Root",
        NULL,
        100,
        CURRENT_TIMESTAMP,
        @loc_caid,
        1,
        CURRENT_TIMESTAMP
    );

INSERT INTO TRANSLATION (LOCALE_CODE, TEXT_KEY, LITERAL) -- CASTELLÀ
VALUES (@loc_esid, @txt_esid, 'Español'),
    (@loc_esid, @txt_caid, 'Catalán'),
    (@loc_esid, @txt_enid, 'Inglés'),
    (@loc_esid, @txt_frid, 'Francés'),
    (@loc_esid, @txt_ptid, 'Portugués'),
    (@loc_caid, @txt_esid, 'Espanyol'),
    (@loc_caid, @txt_caid, 'Català'),
    (@loc_caid, @txt_enid, 'Anglès'),
    (@loc_caid, @txt_frid, 'Francès'),
    (@loc_caid, @txt_ptid, 'Portuguès'),
    (@loc_enid, @txt_esid, 'Spanish'),
    (@loc_enid, @txt_caid, 'Catalan'),
    (@loc_enid, @txt_enid, 'English'),
    (@loc_enid, @txt_frid, 'French'),
    (@loc_enid, @txt_ptid, 'Portuguese'),
    (@loc_frid, @txt_esid, 'Espagnol'),
    (@loc_frid, @txt_caid, 'Catalan'),
    (@loc_frid, @txt_enid, 'Anglais'),
    (@loc_frid, @txt_frid, 'Français'),
    (@loc_frid, @txt_ptid, 'Portugais'),
    (@loc_ptid, @txt_esid, 'Espanhol'),
    (@loc_ptid, @txt_caid, 'Catalão'),
    (@loc_ptid, @txt_enid, 'Inglês'),
    (@loc_ptid, @txt_frid, 'Francês'),
    (@loc_ptid, @txt_ptid, 'Português');

