// Fitxer de definició proto pels serveis del mòdul LSTMOD.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.34.2
// 	protoc        v5.28.2
// source: lstmod/lst_option_entry.proto

package __

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Definició dels elements de les llistes d'opcions.
type LstOptionEntry struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	BaseEntity *ModelEntity   `protobuf:"bytes,1,opt,name=base_entity,json=baseEntity,proto3" json:"base_entity,omitempty"`
	List       *LstOptionList `protobuf:"bytes,2,opt,name=list,proto3" json:"list,omitempty"`
	Index      int32          `protobuf:"varint,3,opt,name=index,proto3" json:"index,omitempty"`
	OptionKey  string         `protobuf:"bytes,4,opt,name=option_key,json=optionKey,proto3" json:"option_key,omitempty"`
	DescKey    *string        `protobuf:"bytes,5,opt,name=desc_key,json=descKey,proto3,oneof" json:"desc_key,omitempty"`
}

func (x *LstOptionEntry) Reset() {
	*x = LstOptionEntry{}
	if protoimpl.UnsafeEnabled {
		mi := &file_lstmod_lst_option_entry_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *LstOptionEntry) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LstOptionEntry) ProtoMessage() {}

func (x *LstOptionEntry) ProtoReflect() protoreflect.Message {
	mi := &file_lstmod_lst_option_entry_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LstOptionEntry.ProtoReflect.Descriptor instead.
func (*LstOptionEntry) Descriptor() ([]byte, []int) {
	return file_lstmod_lst_option_entry_proto_rawDescGZIP(), []int{0}
}

func (x *LstOptionEntry) GetBaseEntity() *ModelEntity {
	if x != nil {
		return x.BaseEntity
	}
	return nil
}

func (x *LstOptionEntry) GetList() *LstOptionList {
	if x != nil {
		return x.List
	}
	return nil
}

func (x *LstOptionEntry) GetIndex() int32 {
	if x != nil {
		return x.Index
	}
	return 0
}

func (x *LstOptionEntry) GetOptionKey() string {
	if x != nil {
		return x.OptionKey
	}
	return ""
}

func (x *LstOptionEntry) GetDescKey() string {
	if x != nil && x.DescKey != nil {
		return *x.DescKey
	}
	return ""
}

var File_lstmod_lst_option_entry_proto protoreflect.FileDescriptor

var file_lstmod_lst_option_entry_proto_rawDesc = []byte{
	0x0a, 0x1d, 0x6c, 0x73, 0x74, 0x6d, 0x6f, 0x64, 0x2f, 0x6c, 0x73, 0x74, 0x5f, 0x6f, 0x70, 0x74,
	0x69, 0x6f, 0x6e, 0x5f, 0x65, 0x6e, 0x74, 0x72, 0x79, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12,
	0x05, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x12, 0x6d, 0x6f, 0x64, 0x65, 0x6c, 0x5f, 0x65, 0x6e,
	0x74, 0x69, 0x74, 0x79, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x1c, 0x6c, 0x73, 0x74, 0x6d,
	0x6f, 0x64, 0x2f, 0x6c, 0x73, 0x74, 0x5f, 0x6f, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x5f, 0x6c, 0x69,
	0x73, 0x74, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0xd1, 0x01, 0x0a, 0x0e, 0x4c, 0x73, 0x74,
	0x4f, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x12, 0x33, 0x0a, 0x0b, 0x62,
	0x61, 0x73, 0x65, 0x5f, 0x65, 0x6e, 0x74, 0x69, 0x74, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b,
	0x32, 0x12, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x4d, 0x6f, 0x64, 0x65, 0x6c, 0x45, 0x6e,
	0x74, 0x69, 0x74, 0x79, 0x52, 0x0a, 0x62, 0x61, 0x73, 0x65, 0x45, 0x6e, 0x74, 0x69, 0x74, 0x79,
	0x12, 0x28, 0x0a, 0x04, 0x6c, 0x69, 0x73, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x14,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x4c, 0x73, 0x74, 0x4f, 0x70, 0x74, 0x69, 0x6f, 0x6e,
	0x4c, 0x69, 0x73, 0x74, 0x52, 0x04, 0x6c, 0x69, 0x73, 0x74, 0x12, 0x14, 0x0a, 0x05, 0x69, 0x6e,
	0x64, 0x65, 0x78, 0x18, 0x03, 0x20, 0x01, 0x28, 0x05, 0x52, 0x05, 0x69, 0x6e, 0x64, 0x65, 0x78,
	0x12, 0x1d, 0x0a, 0x0a, 0x6f, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x5f, 0x6b, 0x65, 0x79, 0x18, 0x04,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x6f, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x4b, 0x65, 0x79, 0x12,
	0x1e, 0x0a, 0x08, 0x64, 0x65, 0x73, 0x63, 0x5f, 0x6b, 0x65, 0x79, 0x18, 0x05, 0x20, 0x01, 0x28,
	0x09, 0x48, 0x00, 0x52, 0x07, 0x64, 0x65, 0x73, 0x63, 0x4b, 0x65, 0x79, 0x88, 0x01, 0x01, 0x42,
	0x0b, 0x0a, 0x09, 0x5f, 0x64, 0x65, 0x73, 0x63, 0x5f, 0x6b, 0x65, 0x79, 0x42, 0x04, 0x5a, 0x02,
	0x2e, 0x2f, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_lstmod_lst_option_entry_proto_rawDescOnce sync.Once
	file_lstmod_lst_option_entry_proto_rawDescData = file_lstmod_lst_option_entry_proto_rawDesc
)

func file_lstmod_lst_option_entry_proto_rawDescGZIP() []byte {
	file_lstmod_lst_option_entry_proto_rawDescOnce.Do(func() {
		file_lstmod_lst_option_entry_proto_rawDescData = protoimpl.X.CompressGZIP(file_lstmod_lst_option_entry_proto_rawDescData)
	})
	return file_lstmod_lst_option_entry_proto_rawDescData
}

var file_lstmod_lst_option_entry_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_lstmod_lst_option_entry_proto_goTypes = []any{
	(*LstOptionEntry)(nil), // 0: proto.LstOptionEntry
	(*ModelEntity)(nil),    // 1: proto.ModelEntity
	(*LstOptionList)(nil),  // 2: proto.LstOptionList
}
var file_lstmod_lst_option_entry_proto_depIdxs = []int32{
	1, // 0: proto.LstOptionEntry.base_entity:type_name -> proto.ModelEntity
	2, // 1: proto.LstOptionEntry.list:type_name -> proto.LstOptionList
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_lstmod_lst_option_entry_proto_init() }
func file_lstmod_lst_option_entry_proto_init() {
	if File_lstmod_lst_option_entry_proto != nil {
		return
	}
	file_model_entity_proto_init()
	file_lstmod_lst_option_list_proto_init()
	if !protoimpl.UnsafeEnabled {
		file_lstmod_lst_option_entry_proto_msgTypes[0].Exporter = func(v any, i int) any {
			switch v := v.(*LstOptionEntry); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	file_lstmod_lst_option_entry_proto_msgTypes[0].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_lstmod_lst_option_entry_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_lstmod_lst_option_entry_proto_goTypes,
		DependencyIndexes: file_lstmod_lst_option_entry_proto_depIdxs,
		MessageInfos:      file_lstmod_lst_option_entry_proto_msgTypes,
	}.Build()
	File_lstmod_lst_option_entry_proto = out.File
	file_lstmod_lst_option_entry_proto_rawDesc = nil
	file_lstmod_lst_option_entry_proto_goTypes = nil
	file_lstmod_lst_option_entry_proto_depIdxs = nil
}
