// Representació de la traducció en 'es', 'ca', 'en', 'fr' i 'pt' de texts.
// createdAt: 24/08/11 dg. JIQ

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.34.2
// 	protoc        v5.28.2
// source: locmod/loc_translation.proto

package __

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Traduccions de les claus de text.
type LocTranslation struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id        *string `protobuf:"bytes,1,opt,name=id,proto3,oneof" json:"id,omitempty"`
	LocaleId  string  `protobuf:"bytes,2,opt,name=locale_id,json=localeId,proto3" json:"locale_id,omitempty"`     // Idioma de la traducció.
	TextKey   string  `protobuf:"bytes,3,opt,name=text_key,json=textKey,proto3" json:"text_key,omitempty"`        // Clau a traduir.
	Literal   string  `protobuf:"bytes,4,opt,name=literal,proto3" json:"literal,omitempty"`                       // Text traduït.
	Iteration int32   `protobuf:"varint,5,opt,name=iteration,proto3" json:"iteration,omitempty"`                  // Iteració de la traducció.
	IsNew     bool    `protobuf:"varint,6,opt,name=is_new,json=isNew,proto3" json:"is_new,omitempty"`             // Indica si la traducció és nova.
	IsUpdated bool    `protobuf:"varint,7,opt,name=is_updated,json=isUpdated,proto3" json:"is_updated,omitempty"` // Indica si la traducció ha estat actualitzada.
	IsDeleted bool    `protobuf:"varint,8,opt,name=is_deleted,json=isDeleted,proto3" json:"is_deleted,omitempty"` // Indica si la traducció ha estat eliminada.
}

func (x *LocTranslation) Reset() {
	*x = LocTranslation{}
	if protoimpl.UnsafeEnabled {
		mi := &file_locmod_loc_translation_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *LocTranslation) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LocTranslation) ProtoMessage() {}

func (x *LocTranslation) ProtoReflect() protoreflect.Message {
	mi := &file_locmod_loc_translation_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LocTranslation.ProtoReflect.Descriptor instead.
func (*LocTranslation) Descriptor() ([]byte, []int) {
	return file_locmod_loc_translation_proto_rawDescGZIP(), []int{0}
}

func (x *LocTranslation) GetId() string {
	if x != nil && x.Id != nil {
		return *x.Id
	}
	return ""
}

func (x *LocTranslation) GetLocaleId() string {
	if x != nil {
		return x.LocaleId
	}
	return ""
}

func (x *LocTranslation) GetTextKey() string {
	if x != nil {
		return x.TextKey
	}
	return ""
}

func (x *LocTranslation) GetLiteral() string {
	if x != nil {
		return x.Literal
	}
	return ""
}

func (x *LocTranslation) GetIteration() int32 {
	if x != nil {
		return x.Iteration
	}
	return 0
}

func (x *LocTranslation) GetIsNew() bool {
	if x != nil {
		return x.IsNew
	}
	return false
}

func (x *LocTranslation) GetIsUpdated() bool {
	if x != nil {
		return x.IsUpdated
	}
	return false
}

func (x *LocTranslation) GetIsDeleted() bool {
	if x != nil {
		return x.IsDeleted
	}
	return false
}

var File_locmod_loc_translation_proto protoreflect.FileDescriptor

var file_locmod_loc_translation_proto_rawDesc = []byte{
	0x0a, 0x1c, 0x6c, 0x6f, 0x63, 0x6d, 0x6f, 0x64, 0x2f, 0x6c, 0x6f, 0x63, 0x5f, 0x74, 0x72, 0x61,
	0x6e, 0x73, 0x6c, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x05,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0xf1, 0x01, 0x0a, 0x0e, 0x4c, 0x6f, 0x63, 0x54, 0x72, 0x61,
	0x6e, 0x73, 0x6c, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x13, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x09, 0x48, 0x00, 0x52, 0x02, 0x69, 0x64, 0x88, 0x01, 0x01, 0x12, 0x1b, 0x0a,
	0x09, 0x6c, 0x6f, 0x63, 0x61, 0x6c, 0x65, 0x5f, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x08, 0x6c, 0x6f, 0x63, 0x61, 0x6c, 0x65, 0x49, 0x64, 0x12, 0x19, 0x0a, 0x08, 0x74, 0x65,
	0x78, 0x74, 0x5f, 0x6b, 0x65, 0x79, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x74, 0x65,
	0x78, 0x74, 0x4b, 0x65, 0x79, 0x12, 0x18, 0x0a, 0x07, 0x6c, 0x69, 0x74, 0x65, 0x72, 0x61, 0x6c,
	0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x6c, 0x69, 0x74, 0x65, 0x72, 0x61, 0x6c, 0x12,
	0x1c, 0x0a, 0x09, 0x69, 0x74, 0x65, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x05, 0x20, 0x01,
	0x28, 0x05, 0x52, 0x09, 0x69, 0x74, 0x65, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x15, 0x0a,
	0x06, 0x69, 0x73, 0x5f, 0x6e, 0x65, 0x77, 0x18, 0x06, 0x20, 0x01, 0x28, 0x08, 0x52, 0x05, 0x69,
	0x73, 0x4e, 0x65, 0x77, 0x12, 0x1d, 0x0a, 0x0a, 0x69, 0x73, 0x5f, 0x75, 0x70, 0x64, 0x61, 0x74,
	0x65, 0x64, 0x18, 0x07, 0x20, 0x01, 0x28, 0x08, 0x52, 0x09, 0x69, 0x73, 0x55, 0x70, 0x64, 0x61,
	0x74, 0x65, 0x64, 0x12, 0x1d, 0x0a, 0x0a, 0x69, 0x73, 0x5f, 0x64, 0x65, 0x6c, 0x65, 0x74, 0x65,
	0x64, 0x18, 0x08, 0x20, 0x01, 0x28, 0x08, 0x52, 0x09, 0x69, 0x73, 0x44, 0x65, 0x6c, 0x65, 0x74,
	0x65, 0x64, 0x42, 0x05, 0x0a, 0x03, 0x5f, 0x69, 0x64, 0x42, 0x04, 0x5a, 0x02, 0x2e, 0x2f, 0x62,
	0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_locmod_loc_translation_proto_rawDescOnce sync.Once
	file_locmod_loc_translation_proto_rawDescData = file_locmod_loc_translation_proto_rawDesc
)

func file_locmod_loc_translation_proto_rawDescGZIP() []byte {
	file_locmod_loc_translation_proto_rawDescOnce.Do(func() {
		file_locmod_loc_translation_proto_rawDescData = protoimpl.X.CompressGZIP(file_locmod_loc_translation_proto_rawDescData)
	})
	return file_locmod_loc_translation_proto_rawDescData
}

var file_locmod_loc_translation_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_locmod_loc_translation_proto_goTypes = []any{
	(*LocTranslation)(nil), // 0: proto.LocTranslation
}
var file_locmod_loc_translation_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_locmod_loc_translation_proto_init() }
func file_locmod_loc_translation_proto_init() {
	if File_locmod_loc_translation_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_locmod_loc_translation_proto_msgTypes[0].Exporter = func(v any, i int) any {
			switch v := v.(*LocTranslation); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	file_locmod_loc_translation_proto_msgTypes[0].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_locmod_loc_translation_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_locmod_loc_translation_proto_goTypes,
		DependencyIndexes: file_locmod_loc_translation_proto_depIdxs,
		MessageInfos:      file_locmod_loc_translation_proto_msgTypes,
	}.Build()
	File_locmod_loc_translation_proto = out.File
	file_locmod_loc_translation_proto_rawDesc = nil
	file_locmod_loc_translation_proto_goTypes = nil
	file_locmod_loc_translation_proto_depIdxs = nil
}
