// Fitxer de definició proto pel domini 'User'.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.34.2
// 	protoc        v5.28.2
// source: locmod/loc_services.proto

package __

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Emprempta digital de string.
type GbTextKeyFingerPrint struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	LastTextKeyId int32 `protobuf:"varint,1,opt,name=last_text_key_id,json=lastTextKeyId,proto3" json:"last_text_key_id,omitempty"`
}

func (x *GbTextKeyFingerPrint) Reset() {
	*x = GbTextKeyFingerPrint{}
	if protoimpl.UnsafeEnabled {
		mi := &file_locmod_loc_services_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GbTextKeyFingerPrint) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GbTextKeyFingerPrint) ProtoMessage() {}

func (x *GbTextKeyFingerPrint) ProtoReflect() protoreflect.Message {
	mi := &file_locmod_loc_services_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GbTextKeyFingerPrint.ProtoReflect.Descriptor instead.
func (*GbTextKeyFingerPrint) Descriptor() ([]byte, []int) {
	return file_locmod_loc_services_proto_rawDescGZIP(), []int{0}
}

func (x *GbTextKeyFingerPrint) GetLastTextKeyId() int32 {
	if x != nil {
		return x.LastTextKeyId
	}
	return 0
}

// Emprempta digital de LocLocale.
type GbLocaleFingerPrint struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	LastLocationId int32 `protobuf:"varint,1,opt,name=last_location_id,json=lastLocationId,proto3" json:"last_location_id,omitempty"`
}

func (x *GbLocaleFingerPrint) Reset() {
	*x = GbLocaleFingerPrint{}
	if protoimpl.UnsafeEnabled {
		mi := &file_locmod_loc_services_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GbLocaleFingerPrint) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GbLocaleFingerPrint) ProtoMessage() {}

func (x *GbLocaleFingerPrint) ProtoReflect() protoreflect.Message {
	mi := &file_locmod_loc_services_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GbLocaleFingerPrint.ProtoReflect.Descriptor instead.
func (*GbLocaleFingerPrint) Descriptor() ([]byte, []int) {
	return file_locmod_loc_services_proto_rawDescGZIP(), []int{1}
}

func (x *GbLocaleFingerPrint) GetLastLocationId() int32 {
	if x != nil {
		return x.LastLocationId
	}
	return 0
}

// Emprempta digital de LocTranslation.
type GbTranslationFingerPrint struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	LastTranslationId int32 `protobuf:"varint,1,opt,name=last_translation_id,json=lastTranslationId,proto3" json:"last_translation_id,omitempty"`
}

func (x *GbTranslationFingerPrint) Reset() {
	*x = GbTranslationFingerPrint{}
	if protoimpl.UnsafeEnabled {
		mi := &file_locmod_loc_services_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GbTranslationFingerPrint) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GbTranslationFingerPrint) ProtoMessage() {}

func (x *GbTranslationFingerPrint) ProtoReflect() protoreflect.Message {
	mi := &file_locmod_loc_services_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GbTranslationFingerPrint.ProtoReflect.Descriptor instead.
func (*GbTranslationFingerPrint) Descriptor() ([]byte, []int) {
	return file_locmod_loc_services_proto_rawDescGZIP(), []int{2}
}

func (x *GbTranslationFingerPrint) GetLastTranslationId() int32 {
	if x != nil {
		return x.LastTranslationId
	}
	return 0
}

// Emprempta digital del mòdul LOCMOD.
type GbSyncLocMod struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	FingerId       int32                     `protobuf:"varint,1,opt,name=finger_id,json=fingerId,proto3" json:"finger_id,omitempty"`
	LocTextKey     *GbTextKeyFingerPrint     `protobuf:"bytes,2,opt,name=loc_text_key,json=locTextKey,proto3,oneof" json:"loc_text_key,omitempty"`
	LocLocale      *GbLocaleFingerPrint      `protobuf:"bytes,3,opt,name=loc_locale,json=locLocale,proto3,oneof" json:"loc_locale,omitempty"`
	LocTranslation *GbTranslationFingerPrint `protobuf:"bytes,4,opt,name=loc_translation,json=locTranslation,proto3,oneof" json:"loc_translation,omitempty"`
}

func (x *GbSyncLocMod) Reset() {
	*x = GbSyncLocMod{}
	if protoimpl.UnsafeEnabled {
		mi := &file_locmod_loc_services_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GbSyncLocMod) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GbSyncLocMod) ProtoMessage() {}

func (x *GbSyncLocMod) ProtoReflect() protoreflect.Message {
	mi := &file_locmod_loc_services_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GbSyncLocMod.ProtoReflect.Descriptor instead.
func (*GbSyncLocMod) Descriptor() ([]byte, []int) {
	return file_locmod_loc_services_proto_rawDescGZIP(), []int{3}
}

func (x *GbSyncLocMod) GetFingerId() int32 {
	if x != nil {
		return x.FingerId
	}
	return 0
}

func (x *GbSyncLocMod) GetLocTextKey() *GbTextKeyFingerPrint {
	if x != nil {
		return x.LocTextKey
	}
	return nil
}

func (x *GbSyncLocMod) GetLocLocale() *GbLocaleFingerPrint {
	if x != nil {
		return x.LocLocale
	}
	return nil
}

func (x *GbSyncLocMod) GetLocTranslation() *GbTranslationFingerPrint {
	if x != nil {
		return x.LocTranslation
	}
	return nil
}

// Petició d'una traducció.
type PrtDownloadTranslation struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UserId int32  `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	LangId string `protobuf:"bytes,2,opt,name=lang_id,json=langId,proto3" json:"lang_id,omitempty"`
	TkeyId string `protobuf:"bytes,3,opt,name=tkey_id,json=tkeyId,proto3" json:"tkey_id,omitempty"`
}

func (x *PrtDownloadTranslation) Reset() {
	*x = PrtDownloadTranslation{}
	if protoimpl.UnsafeEnabled {
		mi := &file_locmod_loc_services_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PrtDownloadTranslation) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PrtDownloadTranslation) ProtoMessage() {}

func (x *PrtDownloadTranslation) ProtoReflect() protoreflect.Message {
	mi := &file_locmod_loc_services_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PrtDownloadTranslation.ProtoReflect.Descriptor instead.
func (*PrtDownloadTranslation) Descriptor() ([]byte, []int) {
	return file_locmod_loc_services_proto_rawDescGZIP(), []int{4}
}

func (x *PrtDownloadTranslation) GetUserId() int32 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *PrtDownloadTranslation) GetLangId() string {
	if x != nil {
		return x.LangId
	}
	return ""
}

func (x *PrtDownloadTranslation) GetTkeyId() string {
	if x != nil {
		return x.TkeyId
	}
	return ""
}

// Resposta a una petició d'una traducció.
type PrtTranslation struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Locale      *string         `protobuf:"bytes,1,opt,name=locale,proto3,oneof" json:"locale,omitempty"`
	TextKey     *string         `protobuf:"bytes,2,opt,name=text_key,json=textKey,proto3,oneof" json:"text_key,omitempty"`
	Translation *LocTranslation `protobuf:"bytes,3,opt,name=translation,proto3,oneof" json:"translation,omitempty"`
}

func (x *PrtTranslation) Reset() {
	*x = PrtTranslation{}
	if protoimpl.UnsafeEnabled {
		mi := &file_locmod_loc_services_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PrtTranslation) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PrtTranslation) ProtoMessage() {}

func (x *PrtTranslation) ProtoReflect() protoreflect.Message {
	mi := &file_locmod_loc_services_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PrtTranslation.ProtoReflect.Descriptor instead.
func (*PrtTranslation) Descriptor() ([]byte, []int) {
	return file_locmod_loc_services_proto_rawDescGZIP(), []int{5}
}

func (x *PrtTranslation) GetLocale() string {
	if x != nil && x.Locale != nil {
		return *x.Locale
	}
	return ""
}

func (x *PrtTranslation) GetTextKey() string {
	if x != nil && x.TextKey != nil {
		return *x.TextKey
	}
	return ""
}

func (x *PrtTranslation) GetTranslation() *LocTranslation {
	if x != nil {
		return x.Translation
	}
	return nil
}

var File_locmod_loc_services_proto protoreflect.FileDescriptor

var file_locmod_loc_services_proto_rawDesc = []byte{
	0x0a, 0x19, 0x6c, 0x6f, 0x63, 0x6d, 0x6f, 0x64, 0x2f, 0x6c, 0x6f, 0x63, 0x5f, 0x73, 0x65, 0x72,
	0x76, 0x69, 0x63, 0x65, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x05, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x1a, 0x19, 0x6c, 0x6f, 0x63, 0x6d, 0x6f, 0x64, 0x2f, 0x6c, 0x6f, 0x63, 0x5f, 0x72,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x1c, 0x6c,
	0x6f, 0x63, 0x6d, 0x6f, 0x64, 0x2f, 0x6c, 0x6f, 0x63, 0x5f, 0x74, 0x72, 0x61, 0x6e, 0x73, 0x6c,
	0x61, 0x74, 0x69, 0x6f, 0x6e, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x3f, 0x0a, 0x14, 0x47,
	0x62, 0x54, 0x65, 0x78, 0x74, 0x4b, 0x65, 0x79, 0x46, 0x69, 0x6e, 0x67, 0x65, 0x72, 0x50, 0x72,
	0x69, 0x6e, 0x74, 0x12, 0x27, 0x0a, 0x10, 0x6c, 0x61, 0x73, 0x74, 0x5f, 0x74, 0x65, 0x78, 0x74,
	0x5f, 0x6b, 0x65, 0x79, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x0d, 0x6c,
	0x61, 0x73, 0x74, 0x54, 0x65, 0x78, 0x74, 0x4b, 0x65, 0x79, 0x49, 0x64, 0x22, 0x3f, 0x0a, 0x13,
	0x47, 0x62, 0x4c, 0x6f, 0x63, 0x61, 0x6c, 0x65, 0x46, 0x69, 0x6e, 0x67, 0x65, 0x72, 0x50, 0x72,
	0x69, 0x6e, 0x74, 0x12, 0x28, 0x0a, 0x10, 0x6c, 0x61, 0x73, 0x74, 0x5f, 0x6c, 0x6f, 0x63, 0x61,
	0x74, 0x69, 0x6f, 0x6e, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x0e, 0x6c,
	0x61, 0x73, 0x74, 0x4c, 0x6f, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x49, 0x64, 0x22, 0x4a, 0x0a,
	0x18, 0x47, 0x62, 0x54, 0x72, 0x61, 0x6e, 0x73, 0x6c, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x46, 0x69,
	0x6e, 0x67, 0x65, 0x72, 0x50, 0x72, 0x69, 0x6e, 0x74, 0x12, 0x2e, 0x0a, 0x13, 0x6c, 0x61, 0x73,
	0x74, 0x5f, 0x74, 0x72, 0x61, 0x6e, 0x73, 0x6c, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x5f, 0x69, 0x64,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x11, 0x6c, 0x61, 0x73, 0x74, 0x54, 0x72, 0x61, 0x6e,
	0x73, 0x6c, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x49, 0x64, 0x22, 0xb2, 0x02, 0x0a, 0x0c, 0x47, 0x62,
	0x53, 0x79, 0x6e, 0x63, 0x4c, 0x6f, 0x63, 0x4d, 0x6f, 0x64, 0x12, 0x1b, 0x0a, 0x09, 0x66, 0x69,
	0x6e, 0x67, 0x65, 0x72, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x08, 0x66,
	0x69, 0x6e, 0x67, 0x65, 0x72, 0x49, 0x64, 0x12, 0x42, 0x0a, 0x0c, 0x6c, 0x6f, 0x63, 0x5f, 0x74,
	0x65, 0x78, 0x74, 0x5f, 0x6b, 0x65, 0x79, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1b, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x47, 0x62, 0x54, 0x65, 0x78, 0x74, 0x4b, 0x65, 0x79, 0x46,
	0x69, 0x6e, 0x67, 0x65, 0x72, 0x50, 0x72, 0x69, 0x6e, 0x74, 0x48, 0x00, 0x52, 0x0a, 0x6c, 0x6f,
	0x63, 0x54, 0x65, 0x78, 0x74, 0x4b, 0x65, 0x79, 0x88, 0x01, 0x01, 0x12, 0x3e, 0x0a, 0x0a, 0x6c,
	0x6f, 0x63, 0x5f, 0x6c, 0x6f, 0x63, 0x61, 0x6c, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32,
	0x1a, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x47, 0x62, 0x4c, 0x6f, 0x63, 0x61, 0x6c, 0x65,
	0x46, 0x69, 0x6e, 0x67, 0x65, 0x72, 0x50, 0x72, 0x69, 0x6e, 0x74, 0x48, 0x01, 0x52, 0x09, 0x6c,
	0x6f, 0x63, 0x4c, 0x6f, 0x63, 0x61, 0x6c, 0x65, 0x88, 0x01, 0x01, 0x12, 0x4d, 0x0a, 0x0f, 0x6c,
	0x6f, 0x63, 0x5f, 0x74, 0x72, 0x61, 0x6e, 0x73, 0x6c, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x04,
	0x20, 0x01, 0x28, 0x0b, 0x32, 0x1f, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x47, 0x62, 0x54,
	0x72, 0x61, 0x6e, 0x73, 0x6c, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x46, 0x69, 0x6e, 0x67, 0x65, 0x72,
	0x50, 0x72, 0x69, 0x6e, 0x74, 0x48, 0x02, 0x52, 0x0e, 0x6c, 0x6f, 0x63, 0x54, 0x72, 0x61, 0x6e,
	0x73, 0x6c, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x88, 0x01, 0x01, 0x42, 0x0f, 0x0a, 0x0d, 0x5f, 0x6c,
	0x6f, 0x63, 0x5f, 0x74, 0x65, 0x78, 0x74, 0x5f, 0x6b, 0x65, 0x79, 0x42, 0x0d, 0x0a, 0x0b, 0x5f,
	0x6c, 0x6f, 0x63, 0x5f, 0x6c, 0x6f, 0x63, 0x61, 0x6c, 0x65, 0x42, 0x12, 0x0a, 0x10, 0x5f, 0x6c,
	0x6f, 0x63, 0x5f, 0x74, 0x72, 0x61, 0x6e, 0x73, 0x6c, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x22, 0x63,
	0x0a, 0x16, 0x50, 0x72, 0x74, 0x44, 0x6f, 0x77, 0x6e, 0x6c, 0x6f, 0x61, 0x64, 0x54, 0x72, 0x61,
	0x6e, 0x73, 0x6c, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x17, 0x0a, 0x07, 0x75, 0x73, 0x65, 0x72,
	0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x06, 0x75, 0x73, 0x65, 0x72, 0x49,
	0x64, 0x12, 0x17, 0x0a, 0x07, 0x6c, 0x61, 0x6e, 0x67, 0x5f, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x06, 0x6c, 0x61, 0x6e, 0x67, 0x49, 0x64, 0x12, 0x17, 0x0a, 0x07, 0x74, 0x6b,
	0x65, 0x79, 0x5f, 0x69, 0x64, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x74, 0x6b, 0x65,
	0x79, 0x49, 0x64, 0x22, 0xb3, 0x01, 0x0a, 0x0e, 0x50, 0x72, 0x74, 0x54, 0x72, 0x61, 0x6e, 0x73,
	0x6c, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x1b, 0x0a, 0x06, 0x6c, 0x6f, 0x63, 0x61, 0x6c, 0x65,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x48, 0x00, 0x52, 0x06, 0x6c, 0x6f, 0x63, 0x61, 0x6c, 0x65,
	0x88, 0x01, 0x01, 0x12, 0x1e, 0x0a, 0x08, 0x74, 0x65, 0x78, 0x74, 0x5f, 0x6b, 0x65, 0x79, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x09, 0x48, 0x01, 0x52, 0x07, 0x74, 0x65, 0x78, 0x74, 0x4b, 0x65, 0x79,
	0x88, 0x01, 0x01, 0x12, 0x3c, 0x0a, 0x0b, 0x74, 0x72, 0x61, 0x6e, 0x73, 0x6c, 0x61, 0x74, 0x69,
	0x6f, 0x6e, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x15, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x2e, 0x4c, 0x6f, 0x63, 0x54, 0x72, 0x61, 0x6e, 0x73, 0x6c, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x48,
	0x02, 0x52, 0x0b, 0x74, 0x72, 0x61, 0x6e, 0x73, 0x6c, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x88, 0x01,
	0x01, 0x42, 0x09, 0x0a, 0x07, 0x5f, 0x6c, 0x6f, 0x63, 0x61, 0x6c, 0x65, 0x42, 0x0b, 0x0a, 0x09,
	0x5f, 0x74, 0x65, 0x78, 0x74, 0x5f, 0x6b, 0x65, 0x79, 0x42, 0x0e, 0x0a, 0x0c, 0x5f, 0x74, 0x72,
	0x61, 0x6e, 0x73, 0x6c, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x32, 0x52, 0x0a, 0x0f, 0x4c, 0x61, 0x6e,
	0x67, 0x75, 0x61, 0x67, 0x65, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x3f, 0x0a, 0x09,
	0x54, 0x72, 0x61, 0x6e, 0x73, 0x6c, 0x61, 0x74, 0x65, 0x12, 0x17, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x2e, 0x4c, 0x6f, 0x63, 0x52, 0x65, 0x71, 0x74, 0x54, 0x72, 0x61, 0x6e, 0x73, 0x6c, 0x61,
	0x74, 0x65, 0x1a, 0x17, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x4c, 0x6f, 0x63, 0x52, 0x65,
	0x73, 0x70, 0x54, 0x72, 0x61, 0x6e, 0x73, 0x6c, 0x61, 0x74, 0x65, 0x22, 0x00, 0x42, 0x04, 0x5a,
	0x02, 0x2e, 0x2f, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_locmod_loc_services_proto_rawDescOnce sync.Once
	file_locmod_loc_services_proto_rawDescData = file_locmod_loc_services_proto_rawDesc
)

func file_locmod_loc_services_proto_rawDescGZIP() []byte {
	file_locmod_loc_services_proto_rawDescOnce.Do(func() {
		file_locmod_loc_services_proto_rawDescData = protoimpl.X.CompressGZIP(file_locmod_loc_services_proto_rawDescData)
	})
	return file_locmod_loc_services_proto_rawDescData
}

var file_locmod_loc_services_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_locmod_loc_services_proto_goTypes = []any{
	(*GbTextKeyFingerPrint)(nil),     // 0: proto.GbTextKeyFingerPrint
	(*GbLocaleFingerPrint)(nil),      // 1: proto.GbLocaleFingerPrint
	(*GbTranslationFingerPrint)(nil), // 2: proto.GbTranslationFingerPrint
	(*GbSyncLocMod)(nil),             // 3: proto.GbSyncLocMod
	(*PrtDownloadTranslation)(nil),   // 4: proto.PrtDownloadTranslation
	(*PrtTranslation)(nil),           // 5: proto.PrtTranslation
	(*LocTranslation)(nil),           // 6: proto.LocTranslation
	(*LocReqtTranslate)(nil),         // 7: proto.LocReqtTranslate
	(*LocRespTranslate)(nil),         // 8: proto.LocRespTranslate
}
var file_locmod_loc_services_proto_depIdxs = []int32{
	0, // 0: proto.GbSyncLocMod.loc_text_key:type_name -> proto.GbTextKeyFingerPrint
	1, // 1: proto.GbSyncLocMod.loc_locale:type_name -> proto.GbLocaleFingerPrint
	2, // 2: proto.GbSyncLocMod.loc_translation:type_name -> proto.GbTranslationFingerPrint
	6, // 3: proto.PrtTranslation.translation:type_name -> proto.LocTranslation
	7, // 4: proto.LanguageService.Translate:input_type -> proto.LocReqtTranslate
	8, // 5: proto.LanguageService.Translate:output_type -> proto.LocRespTranslate
	5, // [5:6] is the sub-list for method output_type
	4, // [4:5] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_locmod_loc_services_proto_init() }
func file_locmod_loc_services_proto_init() {
	if File_locmod_loc_services_proto != nil {
		return
	}
	file_locmod_loc_requests_proto_init()
	file_locmod_loc_translation_proto_init()
	if !protoimpl.UnsafeEnabled {
		file_locmod_loc_services_proto_msgTypes[0].Exporter = func(v any, i int) any {
			switch v := v.(*GbTextKeyFingerPrint); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_locmod_loc_services_proto_msgTypes[1].Exporter = func(v any, i int) any {
			switch v := v.(*GbLocaleFingerPrint); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_locmod_loc_services_proto_msgTypes[2].Exporter = func(v any, i int) any {
			switch v := v.(*GbTranslationFingerPrint); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_locmod_loc_services_proto_msgTypes[3].Exporter = func(v any, i int) any {
			switch v := v.(*GbSyncLocMod); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_locmod_loc_services_proto_msgTypes[4].Exporter = func(v any, i int) any {
			switch v := v.(*PrtDownloadTranslation); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_locmod_loc_services_proto_msgTypes[5].Exporter = func(v any, i int) any {
			switch v := v.(*PrtTranslation); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	file_locmod_loc_services_proto_msgTypes[3].OneofWrappers = []any{}
	file_locmod_loc_services_proto_msgTypes[5].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_locmod_loc_services_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_locmod_loc_services_proto_goTypes,
		DependencyIndexes: file_locmod_loc_services_proto_depIdxs,
		MessageInfos:      file_locmod_loc_services_proto_msgTypes,
	}.Build()
	File_locmod_loc_services_proto = out.File
	file_locmod_loc_services_proto_rawDesc = nil
	file_locmod_loc_services_proto_goTypes = nil
	file_locmod_loc_services_proto_depIdxs = nil
}
