// Fitxer de definició de les estructures proto GLOBALs.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.34.2
// 	protoc        v5.28.2
// source: gbl_global.proto

package __

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Representació d'un error amb codi i missatge opcional.
type GbError struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Code    GbErrorCode `protobuf:"varint,1,opt,name=code,proto3,enum=proto.GbErrorCode" json:"code,omitempty"`
	Message *string     `protobuf:"bytes,2,opt,name=message,proto3,oneof" json:"message,omitempty"`
}

func (x *GbError) Reset() {
	*x = GbError{}
	if protoimpl.UnsafeEnabled {
		mi := &file_gbl_global_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GbError) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GbError) ProtoMessage() {}

func (x *GbError) ProtoReflect() protoreflect.Message {
	mi := &file_gbl_global_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GbError.ProtoReflect.Descriptor instead.
func (*GbError) Descriptor() ([]byte, []int) {
	return file_gbl_global_proto_rawDescGZIP(), []int{0}
}

func (x *GbError) GetCode() GbErrorCode {
	if x != nil {
		return x.Code
	}
	return GbErrorCode_GB_ERROR_CODE_UNSPECIFIED
}

func (x *GbError) GetMessage() string {
	if x != nil && x.Message != nil {
		return *x.Message
	}
	return ""
}

// Representació d'una resposta de 'rebut' amb codi i missatge d'error.
type GbRespAcknoledge struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Error *GbError `protobuf:"bytes,1,opt,name=error,proto3,oneof" json:"error,omitempty"`
}

func (x *GbRespAcknoledge) Reset() {
	*x = GbRespAcknoledge{}
	if protoimpl.UnsafeEnabled {
		mi := &file_gbl_global_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GbRespAcknoledge) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GbRespAcknoledge) ProtoMessage() {}

func (x *GbRespAcknoledge) ProtoReflect() protoreflect.Message {
	mi := &file_gbl_global_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GbRespAcknoledge.ProtoReflect.Descriptor instead.
func (*GbRespAcknoledge) Descriptor() ([]byte, []int) {
	return file_gbl_global_proto_rawDescGZIP(), []int{1}
}

func (x *GbRespAcknoledge) GetError() *GbError {
	if x != nil {
		return x.Error
	}
	return nil
}

// Representació de la cerca pel seu identificador únic.
type GbReqtInstanceById struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id int32 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
}

func (x *GbReqtInstanceById) Reset() {
	*x = GbReqtInstanceById{}
	if protoimpl.UnsafeEnabled {
		mi := &file_gbl_global_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GbReqtInstanceById) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GbReqtInstanceById) ProtoMessage() {}

func (x *GbReqtInstanceById) ProtoReflect() protoreflect.Message {
	mi := &file_gbl_global_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GbReqtInstanceById.ProtoReflect.Descriptor instead.
func (*GbReqtInstanceById) Descriptor() ([]byte, []int) {
	return file_gbl_global_proto_rawDescGZIP(), []int{2}
}

func (x *GbReqtInstanceById) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

// Representació de la cerca d'instàncies d'entitat per una cadena de caràcters.
type GbReqtInstanceByString struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Str string `protobuf:"bytes,1,opt,name=str,proto3" json:"str,omitempty"`
}

func (x *GbReqtInstanceByString) Reset() {
	*x = GbReqtInstanceByString{}
	if protoimpl.UnsafeEnabled {
		mi := &file_gbl_global_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GbReqtInstanceByString) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GbReqtInstanceByString) ProtoMessage() {}

func (x *GbReqtInstanceByString) ProtoReflect() protoreflect.Message {
	mi := &file_gbl_global_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GbReqtInstanceByString.ProtoReflect.Descriptor instead.
func (*GbReqtInstanceByString) Descriptor() ([]byte, []int) {
	return file_gbl_global_proto_rawDescGZIP(), []int{3}
}

func (x *GbReqtInstanceByString) GetStr() string {
	if x != nil {
		return x.Str
	}
	return ""
}

var File_gbl_global_proto protoreflect.FileDescriptor

var file_gbl_global_proto_rawDesc = []byte{
	0x0a, 0x10, 0x67, 0x62, 0x6c, 0x5f, 0x67, 0x6c, 0x6f, 0x62, 0x61, 0x6c, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x12, 0x05, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x16, 0x67, 0x62, 0x6c, 0x5f, 0x65,
	0x6e, 0x75, 0x6d, 0x65, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x22, 0x5c, 0x0a, 0x07, 0x47, 0x62, 0x45, 0x72, 0x72, 0x6f, 0x72, 0x12, 0x26, 0x0a, 0x04,
	0x63, 0x6f, 0x64, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x12, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x2e, 0x47, 0x62, 0x45, 0x72, 0x72, 0x6f, 0x72, 0x43, 0x6f, 0x64, 0x65, 0x52, 0x04,
	0x63, 0x6f, 0x64, 0x65, 0x12, 0x1d, 0x0a, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x09, 0x48, 0x00, 0x52, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65,
	0x88, 0x01, 0x01, 0x42, 0x0a, 0x0a, 0x08, 0x5f, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x22,
	0x47, 0x0a, 0x10, 0x47, 0x62, 0x52, 0x65, 0x73, 0x70, 0x41, 0x63, 0x6b, 0x6e, 0x6f, 0x6c, 0x65,
	0x64, 0x67, 0x65, 0x12, 0x29, 0x0a, 0x05, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x0b, 0x32, 0x0e, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x47, 0x62, 0x45, 0x72, 0x72,
	0x6f, 0x72, 0x48, 0x00, 0x52, 0x05, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x88, 0x01, 0x01, 0x42, 0x08,
	0x0a, 0x06, 0x5f, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x22, 0x24, 0x0a, 0x12, 0x47, 0x62, 0x52, 0x65,
	0x71, 0x74, 0x49, 0x6e, 0x73, 0x74, 0x61, 0x6e, 0x63, 0x65, 0x42, 0x79, 0x49, 0x64, 0x12, 0x0e,
	0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x02, 0x69, 0x64, 0x22, 0x2a,
	0x0a, 0x16, 0x47, 0x62, 0x52, 0x65, 0x71, 0x74, 0x49, 0x6e, 0x73, 0x74, 0x61, 0x6e, 0x63, 0x65,
	0x42, 0x79, 0x53, 0x74, 0x72, 0x69, 0x6e, 0x67, 0x12, 0x10, 0x0a, 0x03, 0x73, 0x74, 0x72, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x73, 0x74, 0x72, 0x42, 0x04, 0x5a, 0x02, 0x2e, 0x2f,
	0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_gbl_global_proto_rawDescOnce sync.Once
	file_gbl_global_proto_rawDescData = file_gbl_global_proto_rawDesc
)

func file_gbl_global_proto_rawDescGZIP() []byte {
	file_gbl_global_proto_rawDescOnce.Do(func() {
		file_gbl_global_proto_rawDescData = protoimpl.X.CompressGZIP(file_gbl_global_proto_rawDescData)
	})
	return file_gbl_global_proto_rawDescData
}

var file_gbl_global_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_gbl_global_proto_goTypes = []any{
	(*GbError)(nil),                // 0: proto.GbError
	(*GbRespAcknoledge)(nil),       // 1: proto.GbRespAcknoledge
	(*GbReqtInstanceById)(nil),     // 2: proto.GbReqtInstanceById
	(*GbReqtInstanceByString)(nil), // 3: proto.GbReqtInstanceByString
	(GbErrorCode)(0),               // 4: proto.GbErrorCode
}
var file_gbl_global_proto_depIdxs = []int32{
	4, // 0: proto.GbError.code:type_name -> proto.GbErrorCode
	0, // 1: proto.GbRespAcknoledge.error:type_name -> proto.GbError
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_gbl_global_proto_init() }
func file_gbl_global_proto_init() {
	if File_gbl_global_proto != nil {
		return
	}
	file_gbl_enumerations_proto_init()
	if !protoimpl.UnsafeEnabled {
		file_gbl_global_proto_msgTypes[0].Exporter = func(v any, i int) any {
			switch v := v.(*GbError); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_gbl_global_proto_msgTypes[1].Exporter = func(v any, i int) any {
			switch v := v.(*GbRespAcknoledge); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_gbl_global_proto_msgTypes[2].Exporter = func(v any, i int) any {
			switch v := v.(*GbReqtInstanceById); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_gbl_global_proto_msgTypes[3].Exporter = func(v any, i int) any {
			switch v := v.(*GbReqtInstanceByString); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	file_gbl_global_proto_msgTypes[0].OneofWrappers = []any{}
	file_gbl_global_proto_msgTypes[1].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_gbl_global_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_gbl_global_proto_goTypes,
		DependencyIndexes: file_gbl_global_proto_depIdxs,
		MessageInfos:      file_gbl_global_proto_msgTypes,
	}.Build()
	File_gbl_global_proto = out.File
	file_gbl_global_proto_rawDesc = nil
	file_gbl_global_proto_goTypes = nil
	file_gbl_global_proto_depIdxs = nil
}
